### ISSUE TITLE
[wpe-2.22] - regression from commit b4fdd980207af05ce9cc295eb4710160bb04db4b

### ISSUE THREAD

**Issue by simi-mathew** [Metrological/WebKitForWayland#924] opened 2022-08-19 05:37 UTC
Reproduction 
URL - https://widgets.metrological.com/lightning/comcast/3feddb77050929e6dac000ad7064cb91?lmt=0&us_privacy=1-N-#app:com.metrological.app.France24
Devices impacted - comcast x1,xclass devices
The changes from https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/b4fdd980207af05ce9cc295eb4710160bb04db4b results in a stalled event after the timeout of 3s and the app displays a spinner wheel

Logs - 
[france24.log](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/9379385/france24.log)

Timestamp - 11:27:28.335916
```2022 Aug 09 11:27:28.160008 WPEFramework[16547]:  0:00:31.473302733 0xac8033c0 TRACE  webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:481:playbackPosition:<play_0x99c71600> Position 0:00:07.725666666
2022 Aug 09 11:27:28.334680 WPEFramework[16547]:  0:00:31.647931648 0xac8033c0 TRACE  webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2042:maxTimeLoaded:maxTimeLoaded: {35770890420/1000000000 = 35.770890}
2022 Aug 09 11:27:28.335229 WPEFramework[16547]:  0:00:31.647972524 0xac8033c0 LOG    webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2060:didLoadingProgress:didLoadingProgress: false
2022 Aug 09 11:27:28.335916 WPEFramework[16547]:  EventDispatcher::dispatchEvent stalled on node VIDEO

**Comment by jacek-skiba-red** [comment] 2022-08-26 13:09
@simi-mathew most probably this commit is fixing the stalled event in France24 progressive playback: 6b2c308
Please confirm.

**Comment by simi-mathew** [comment] 2022-08-29 11:35
@jacek-skiba-red 
I had checked with the changes in https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/6b2c308873ae42e9ffd87a189c96541a3735dcfc and that does not fix the issue

**Comment by jacek-skiba-red** [comment] 2022-10-27 18:32
@simi-mathew Indeed, https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/6b2c308873ae42e9ffd87a189c96541a3735dcfc is not helping here.

Lightning France24 app for live streaming is using MSE (via hls.js) and for other content progressive streaming.
Spinner issue is seen only during progressive playback. When during playback stalled event will be send from video tag then spinner will show. For MSE it's not the case. It can be simulated from Web Inspector:
```
const event = document.createEvent('Event');
event.initEvent('stalled', true, true);
document.getElementsByTagName('video')[0].dispatchEvent(event)
```

Before https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/b4fdd980207af05ce9cc295eb4710160bb04db4b was merged we had situation that end buffer was equal to current time:
```
document.getElementsByTagName('video')[0].currentTime == document.getElementsByTagName('video')[0].buffered.end(0)
```

Going to code, `buffer.end()` was calculated from `MediaPlayerPrivateGStreamer::maxTimeLoaded()`, where we take value from `loaded = m_cachedPosition`:
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L1970

`m_cachedPosition` is updated constantly during playback in playbackPosition() method.
In general, `maxTimeLoaded()` return value did not reflect reality, because we did not had correlation between fetched data and `buffer.end` value. However, `buffer.end` property was constantly updated. 

https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/b4fdd980207af05ce9cc295eb4710160bb04db4b adds estimated correlation between fetched data from network and `buffer.end` value for progressive playback. `m_maxTimeLoaded` is updated based on `webkit-network-statistics` message send from `WebkitWebSource`.

In your reproduction, for 3 seconds `m_maxTimeLoaded` value was not updated:
```
11:27:25.179496    maxTimeLoaded: {35770890420/1000000000 = 35.770890}
11:27:28.334680    maxTimeLoaded: {35770890420/1000000000 = 35.770890}
11:27:28.335916    EventDispatcher::dispatchEvent stalled on node VIDEO
```

I cannot reproduce your problem on broadcom based STB with Gstreamer 1.10 and 1.18.

What I can propose:
* workaround solution: increase 3 sec timer to some greater value. HTML spec is not defining what timeout should be specified for stalled event

https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/html/HTMLMediaElement.cpp#L2886 
* harded solution: adjust `appsrc` parameters related to `webKitWebSrcNeedData` to not have so much delays between subsequent data requests:
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.cpp#L342

**Comment by eocanha** [comment] 2022-11-23 18:39
How can stalled events be a problem in MSE anymore after https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/2fdbc3c7aa64b8dd8b4b151847da7c102a7e1d5d ?

Am I understanding the Issue wrongly and it's actually related to non-MSE video? The demo test case app uses MSE, but some of your comments talk about WebKitWebSrc (the source element used for regular video). Where does the actual problem happen?

**Comment by jacek-skiba-red** [comment] 2022-11-25 06:59
@eocanha issue is only related to progressive streaming where France24 is using for main content MSE streaming, and for other progressive. 

> Spinner issue is seen only during progressive playback. When during playback stalled event will be send from video tag then spinner will show. For MSE it's not the case.

**Comment by eocanha** [comment] 2022-12-09 14:39
I've tried multiple approaches to solve this issue:

* Reworked player private readyState computation to be more monotonic, but even though it solved the issue, not all the intermediate states are traversed and also the "stalled" event is never triggered. Undid these changes.
* Debugged buffering. GstQueue2 won't signal buffering levels in all the circumstances. Abandoned this path.
* Focused on analyzing the patch that caused the regression. The previous implementation used cachedPosition to estimate maxTimeLoaded (more continuous, no stalls), while the new one uses the actual amount of downloaded data (chunky, trigger stalls).
* Increased the timeout to detect stall, but that isn't actually a good solution and causes other problems. Abandoned this path.
* Exposed the WebKitWebSrc paused attribute and declared didLoadingProgress when the source is paused. Unfortunately, the source is paused a big percent of the time, so while this solved the issue, it isn't useful to detect stalls when the bandwidth is too low.

After all those attempts, I've come up with https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/993. It takes into account when WebKitWebSrc is paused (not wanting to download anything from the network) and doesn't declare false on didLoadingProgress() in that case. If currentTime goes beyond the maximum downloaded time, it returns false.

If you confirm that it solves the bug for you, I'll merge it. I's gone fine in the local tests I've done, where I triggered "network issues" by unplugging the Raspberry Pi ethernet cable.

**Comment by simi-mathew** [comment] 2022-12-12 03:54
Hi @eocanha 
Thanks ! Let me test the patch out and get back to you.

**Comment by eocanha** [comment] 2023-02-21 09:50
I'm removing this Issue from my to-do/attention queue. Let me know if the proposed patch has been enough to solve the issue or if you need more work from me.

**Comment by calvaris** [comment] 2023-02-27 12:37
Considering reopening this in the future if keeps being a problem.

**Closed as completed by calvaris** 2023-02-27 12:37 UTC
