### ISSUE TITLE
[wpe-2.28] crash in InspectorAnimationAgent

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#842] opened 2022-05-04 19:56 UTC
This was observed on Tubi (https://ott-comcast.tubitv.com/?animationComplete=true&logExposure=true) with HTTP remote web inspector. 

```
(gdb) bt
#0  WebCore::Node::renderer () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebCore/dom/Node.h:400
#1  WebCore::ContainerNode::renderer () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebCore/rendering/RenderElement.h:478
#2  buildObjectForKeyframes () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebCore/inspector/agents/InspectorAnimationAgent.cpp:120
#3  buildObjectForEffect () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebCore/inspector/agents/InspectorAnimationAgent.cpp:214
#4  0xb2c65588 in WebCore::InspectorAnimationAgent::bindAnimation () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebCore/inspector/agents/InspectorAnimationAgent.cpp:539
#5  0xb2c65932 in WebCore::InspectorAnimationAgent::enable () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebCore/inspector/agents/InspectorAnimationAgent.cpp:269
#6  0xb34c1182 in Inspector::AnimationBackendDispatcher::enable () at DerivedSources/JavaScriptCore/inspector/InspectorBackendDispatchers.cpp:132
#7  0xb34b57ea in Inspector::AnimationBackendDispatcher::dispatch () at DerivedSources/JavaScriptCore/inspector/InspectorBackendDispatchers.cpp:118
#8  0xb34df8a8 in Inspector::BackendDispatcher::dispatch () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/JavaScriptCore/inspector/InspectorBackendDispatcher.cpp:180
#9  0xb22b7078 in IPC::callMemberFunctionImpl<WebKit::WebPage, void (WebKit::WebPage::*)(WTF::String const&, WTF::String const&), std::tuple<WTF::String, WTF::String>, 0u, 1u> () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Platform/IPC/HandleMessage.h:41
#10 IPC::callMemberFunction<WebKit::WebPage, void (WebKit::WebPage::*)(WTF::String const&, WTF::String const&), std::tuple<WTF::String, WTF::String>, std::integer_sequence<unsigned int, 0u, 1u> > () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Platform/IPC/HandleMessage.h:47
#11 IPC::handleMessage<Messages::WebPage::SendMessageToTargetBackend, WebKit::WebPage, void (WebKit::WebPage::*)(WTF::String const&, WTF::String const&)> () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Platform/IPC/HandleMessage.h:120
#12 WebKit::WebPage::didReceiveWebPageMessage () at DerivedSources/WebKit/WebPageMessageReceiver.cpp:1174
#13 0xb2329894 in IPC::MessageReceiverMap::dispatchMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Platform/IPC/MessageReceiverMap.cpp:123
#14 0xb243a192 in WebKit::WebProcess::didReceiveMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/WebProcess/WebProcess.cpp:746
#15 0xb23249d0 in IPC::Connection::dispatchMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Platform/IPC/Connection.cpp:1008
#16 0xb232765a in IPC::Connection::dispatchMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Platform/IPC/Connection.cpp:1077
#17 0xb2327c00 in IPC::Connection::dispatchOneIncomingMessage () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Platform/IPC/Connection.cpp:1146
#18 0xb3881040 in WTF::Function<void ()>::operator()() const () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WTF/wtf/Function.h:84
#19 WTF::RunLoop::performWork () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WTF/wtf/RunLoop.cpp:124
#20 0xb38b223e in operator() () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:68
#21 _FUN () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:70
#22 0xb0dbe864 in g_main_dispatch (context=...) at ../glib-2.62.4/glib/gmain.c:3216
#23 g_main_context_dispatch (context=...) at ../glib-2.62.4/glib/gmain.c:3885
#24 0xb0dbe9ce in g_main_context_iterate (context=..., block=..., dispatch=..., self=...) at ../glib-2.62.4/glib/gmain.c:3958
#25 0xb0dbed08 in g_main_loop_run (loop=...) at ../glib-2.62.4/glib/gmain.c:4152
#26 0xb38b2994 in WTF::RunLoop::run () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96
#27 0xb2499cc6 in WebKit::AuxiliaryProcessMain<WebKit::WebProcess, WebKit::WebProcessMainWPE> () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+f049f4091f-r0/git/Source/WebKit/Shared/AuxiliaryProcessMain.h:68
#28 0xb1e8798e in __libc_start_main (main=..., argc=..., argv=..., init=..., fini=..., rtld_fini=..., stack_end=...) at libc-start.c:308
#29 0x00010664 in _start () at ../sysdeps/arm/start.S:126
```

possibly already fixed upstream with https://github.com/WebKit/WebKit-http/commit/3b8dccc11d0e93482e852efdc79a607c4a7cad7b

**Comment by magomez** [comment] 2022-05-10 14:07
The URL is geoblocked and I can't reproduce the issue, but the commit you mention seems to be the fix for it. @emutavchi, I've backported the changes and I'm attaching a patch here so you can test whether this gets fixed. Could you give it a try, please? If the patch fixes the issue, I'll commit it to the 2.28 branch.

[fix-web-animations-crash.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8662215/fix-web-animations-crash.patch.txt)

**Comment by emutavchi** [comment] 2022-05-17 17:41
@magomez it doesn't crash for me with above change.

**Comment by magomez** [comment] 2022-05-18 09:48
> @magomez it doesn't crash for me with above change.

Great! patch committed and pushed. Please verify and close this. Thanks!

**Comment by woutermeek** [comment] 2022-05-23 06:48
@emutavchi if an issue comes up with the patch, please re-open.

**Closed as completed by woutermeek** 2022-05-23 06:48 UTC
