### ISSUE TITLE
Game Webpage is not opening 

### ISSUE THREAD

**Issue by nrajan002c** [Metrological/WebKitForWayland#599] opened 2019-05-07 14:56 UTC
Hi @wouterlucas 
Gaming web pages like 'Crossy Road', 'Carror Mania2' are not opening sometimes. 
It is getting stuck while loading.  We have the image of wpe-20170728 branch 084c5cb53d168ee6addb7030bbd79c2334a4f39a revision.

But the same urls are loading fine in earlier version c699f32f92e227955b252528ed8ececa6118793e

Can you please check this.
URL: https://comcast.play.works/prod/reg/apps/crossy_road/index.html?firstLaunch=1&parent=portal
https://comcast.play.works/prod/reg/apps/carrot_mania2/index.html?parent=portal

**Comment by nrajan002c** [comment] 2019-05-07 17:30
I have manually created the core dump when the loading is at stuck.
Please check it . 
[crossy_road_core.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/3153838/crossy_road_core.txt)

**Comment by magomez** [comment] 2019-05-09 09:28
Adding this to my TODO. I'll check it as soon as my hands are free, hopefully next week.

**Comment by nrajan002c** [comment] 2019-05-10 16:56
Hi @magomez @zdobersek ,
This issue is happening after this commit https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/89f24352472e015403d45ccba0139df7b7bcd055#diff-7492b230165502276f2de3e2f1526e1e .
I tested the url with/without this commit. It is loading fine without this change.
Can you please give your suggestion on this.

**Comment by magomez** [comment] 2019-05-14 11:00
@nambirajang, could you tell me the versions you're using for WPEBackend and WPEBackend-rdk as well? So I can get an environment as close to yours as possible.

**Comment by nrajan002c** [comment] 2019-05-14 13:00
Hi @magomez ,
We are using the below version,
wpe-backend-rdk 99c0f3fafd6e71552bd42e89540175d646e15b7d
wpe-backend b6753c535b5be0db330001ff13387c91d53b48bc
wpe-webkit 084c5cb53d168ee6addb7030bbd79c2334a4f39a

**Comment by magomez** [comment] 2019-05-16 10:31
As @nambirajang found, there are 2 problematic commits here: 89f24352472e015403d45ccba0139df7b7bcd055 and then 9bdb033861b105b08dc9839d1458513155bcedab. The first one is not really wrong, it's just missing a detail, but the second one is a backport of an upstream change that seems to be causing troubles on this old branch. The fix for this would be reverting 9bdb033861b105b08dc9839d1458513155bcedab and adding an small fix after 89f24352472e015403d45ccba0139df7b7bcd055.

I've already commented this with @nambirajang and sent him a patch that fixes the issue for me. We just need to get sure that the issue is fixed for you environment as well.

**Comment by nrajan002c** [comment] 2019-05-16 13:37
Hi @magomez ,
I reverted 9bdb033 and added your fix. Now the URL is opening fine in STB.
Thanks.

**Comment by modeveci** [comment] 2023-09-21 10:53
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!

**Closed as not planned by modeveci** 2023-09-21 10:53 UTC
