### ISSUE TITLE
[JSC] Webprocess crash with "checkConn" Signature de to SIGSEGV

### ISSUE THREAD

**Issue by Shiva367** [Metrological/WebKitForWayland#1003] opened 2023-01-10 08:59 UTC
Description:
This issue is happening in both MIPS and ARM devices (Arris Xi6, Arris XG1v4, Xione_US[Real], Xione_US[BCOM], Hisense MWR & MWR50, TXi6, and Pace devices also). The most affected device is Xione_US[BCOM].

**App:** Peacock, **Frequency:** 0.2%

**Scenario:**
1.Load 5.9p4s1 in bcom xione box .
2. Launch the peacock app.
3. Play any HLS VOD content and do some trick play.
4. Let it play till EOS.
5. Observe the browser crash.

wpe-commit:
55b51e9b8c7a2cc7030e6f984fa317f3bf1bdc41

Full-Stacktrace:
[Stackwalk.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10380784/Stackwalk.txt)

**Comment by guijemont** [comment] 2023-01-10 15:39
Looking at the stack trace, it looks like some kind of stack/memory corruption:
   - frame 3: `JSC::Heap::collectInCollectorThread()` calls `JSC::Heap::runCurrentPhase()` with argument `conn = GCConductor::Collector`
 - frame 2: `JSC::Heap::runCurrentPhase()` forwards that `conn` argument to `JSC::Heap::checkConn()`
 - frame 1: `JSC::Heap::checkConn()` has an assert triggering because `conn` is neither `GCConductor::Mutator` nor `GCConductor::Collector`. Without a memory corruption, it has to be `GCConductor::Collector` as this is the value that was passed.
 
 This means that to investigate further, I would need a way to reproduce the issue locally, so I would need either a reduced test case that I can run on e.g. a raspberry pi 3, or a way to run on one of the devices I have the reproduction scenario, with the ability to recompile WebKit with different options (especially with debug symbols) and attach a debugger.

**Comment by Shiva367** [comment] 2023-01-12 13:23
@guijemont 
So far we can't able to reproduce the issue from our side, the scenario is observed from the logs.

**Thread_state:** 
[Thread_state.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10401512/Thread_state.txt)
**Minidump or symbol_debug:**
[minidump.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10401536/minidump.zip)

**Reproduction Scenario:**
Launch the Peacock app, Play any content till the End-Of-Stream and do some trick plays.

**Comment by guijemont** [comment] 2023-01-12 17:55
Could you provide symbols that match the minidump? (e.g. using `dump_syms`  from breakpad)

**Comment by guijemont** [comment] 2023-01-12 18:13
> Could you provide symbols that match the minidump? (e.g. using `dump_syms` from breakpad)

Note that given the problem, analyzing a minidump or core file doesn't have high chance of helping us much though.

**Comment by Shiva367** [comment] 2023-01-18 05:14
> Description: This issue is happening in both MIPS and ARM devices (Arris Xi6, Arris XG1v4, Xione_US[Real], Xione_US[BCOM], Hisense MWR & MWR50, TXi6, and Pace devices also). The most affected device is Xione_US[BCOM].
> 
> **App:** Peacock, **Frequency:** 0.2%
> 
> **Scenario:** 1.Load 5.9p4s1 in bcom xione box . 2. Launch the peacock app. 3. Play any HLS VOD content and do some trick play. 4. Let it play till EOS. 5. Observe the browser crash.
> 
> wpe-commit: [55b51e9](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/55b51e9b8c7a2cc7030e6f984fa317f3bf1bdc41)
> 
> Full-Stacktrace: [Stackwalk.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10380784/Stackwalk.txt)

@guijemont  in this StackWalk.txt which has all the symbols got resolved by using the break pad only and it also contains all the other threads processes also, 

The exact crashed symbols,

**Thread 48 (crashed)
 0  libWPEWebKit-0.1.so.2.2.6!WTFCrash [Assertions.cpp : 255 + 0xc]
 1  libWPEWebKit-0.1.so.2.2.6!JSC::Heap::checkConn(JSC::GCConductor) [Heap.cpp : 1138 + 0x3]
 2  libWPEWebKit-0.1.so.2.2.6!JSC::Heap::runCurrentPhase(JSC::GCConductor, JSC::CurrentThreadState*) [Heap.cpp : 1143 + 0x3]
 3  libWPEWebKit-0.1.so.2.2.6!JSC::Heap::collectInCollectorThread() [Heap.cpp : 1109 + 0x9]
 4  libWPEWebKit-0.1.so.2.2.6!JSC::Heap::Thread::work() [Heap.cpp : 260 + 0x5]
 5  libWPEWebKit-0.1.so.2.2.6!call [AutomaticThread.cpp : 223 + 0x3]
 6  libWPEWebKit-0.1.so.2.2.6!WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) [Function.h : 56 + 0x7]
 7  libWPEWebKit-0.1.so.2.2.6!wtfThreadEntryPoint [ThreadingPthreads.cpp : 215 + 0x3]
 8  libpthread-2.31.so!start_thread [pthread_create.c : 477 + 0x1]
 9  libc-2.31.so!clone + 0x3a**

Crash symbol callstack:
`WTFCrash
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/WTF/wtf/Assertions.cpp:255

checkConn
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1138

finishChangingPhase
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1534

runCurrentPhase
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1151

collectInCollectorThread
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1109

work
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/JavaScriptCore/heap/Heap.cpp:260

call
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/WTF/wtf/AutomaticThread.cpp:223

entryPoint
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/WTF/wtf/Function.h:56

wtfThreadEntryPoint
/usr/src/debug/lib32-wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215

start_thread
/usr/src/debug/lib32-glibc/2.31+gitAUTOINC+1094741224-r0/git/nptl/pthread_create.c:477

clone
:
`
The symbols are resolved with the minidump by using breakpad only, can you please clarify what exact information you needed?

**Comment by guijemont** [comment] 2023-01-18 11:08
> The symbols are resolved with the minidump by using breakpad only, can you please clarify what exact information you needed?


I am hoping that the minidump contains more information on the state of memory than what's in the stack trace, namely values of variables and parameters. I know that from a minidump and symbols file I can generate a core file, that hopefully would allow me to see that kind of information in gdb. I have not worked with minidumps in a while though, so maybe I'm mistaken?

**Comment by GlebNovodranPE** [comment] 2023-05-22 09:46
Hi @guijemont ,
I will provide the crash minidump and the debug symbols through Özgür in the corporate Slack.
Unfortunately, there is no simplified way to reproduce the problem. Also, QAs were not able not manually reproduce it on rack, following the steps above, and generate a core dump.

However, we see rather many instances of the problem in the field. What we can do, at this point, is to add some additional logging to WPEWebKit and push this build into the field, to a limited number of devices.
I have some doubts if it is going to be helpful, since it  is a corruption issue, but if you think it might help with the investigation, kindly let me know. Maybe, if it is a case of some creation/destruction race, than the additional logging might tell you something?

**Comment by guijemont** [comment] 2023-07-02 20:43
Hi @GlebNovodranPE !

I have pushed a branch with extra logging [here](https://github.com/guijemont/webkit-old/tree/issue-1003-debug). Note that it contains 3 commits above the branch that you were using.
It would be great if you can manage to reproduce the issue with these changes.
Then, to further debug the issue, I would need:
 - the same data as last time (minidump of crashing process + symbol files matching the binaries)
 - the logging output from WebKit of the same run. This is normally on stderr. If you have a hard time capturing it in your environment, you can make WebKit log to a file by changing [DataLog.cpp](https://github.com/guijemont/webkit-old/blob/a30ee142a8a6ab8f714a705cf42b8fb5c4e59f4d/Source/WTF/wtf/DataLog.cpp#L41) to set `DATA_LOG_TO_FILE` to `1` and `DATA_LOG_FILENAME` to the base name with full path of where you want the log saved (WebKit will add `".<pid>.txt"` to that).
 
 The  log file should contain a lot of messages from the garbage collector, and at the end, a line starting with "JSC::Heap::checkConn failing:" followed by a stack trace (note that it's note the stack trace of the point of crash, but of the last time that `mutatorHasConnBit` has been set in the heap's `m_worldState`)

**Comment by guijemont** [comment] 2023-07-02 20:47
> The log file should contain a lot of messages from the garbage collector, and at the end, a line starting with "JSC::Heap::checkConn failing:" followed by a stack trace (note that it's note the stack trace of the point of crash, but of the last time that `mutatorHasConnBit` has been set in the heap's `m_worldState`)

In case the GC logging is slowing down the application too much, you can remove [this commit](https://github.com/guijemont/webkit-old/commit/918c24eeb4e96349c4f79514150ce28b7a07c461) to disable them or (better) change the value to `GCLogging::Basic` to have fewer messages.

**Comment by modeveci** [comment] 2023-09-25 12:04
@GlebNovodranPE As per your update that this is not observed on 2.28 (yet). Can we close this ticket? thank you!

**Comment by GlebNovodranPE** [comment] 2023-09-25 13:30
@modeveci , yes we don't see it with 2.28 still. Let's close it.

**Closed as completed** 2023-09-25 13:34 UTC
