### ISSUE TITLE
Canvas game is not working in few platforms

### ISSUE THREAD

**Issue by nrajan002c** [Metrological/WebKitForWayland#916] opened 2022-07-26 16:06 UTC
Hi @magomez 
After this code change https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/5d7f2eeeac252561d8db62a93c07e3f60452ee87 , it is causing regression issues few other platforms.
" A black screen with Audio seen after the Ad in Food Smash Game" is observed.

We will attach the logs and platform details shortly.

**Comment by coderscollection** [comment] 2022-07-27 11:38
**Apologies. My name is john.nessworthy from the apps team in sky. I accidentally used my own git account to comment.**

Issues observed on llama device. The problem is that running play.works/food smash results in a black screen appearing after the ads in QS009.   The ad appears when the application is started - with the result that the actual game screen never appears. This is 100% reproducible. The same does not happen in a QS008 build. 
I investigated the issue and concluded that the patch

SRC_URI += "[file://2.22.6/0305-Bring-back-the-compositor-buffer-that-was-removed.patch](file://2.22.0.6/0305-Bring-back-the-compositor-buffer-that-was-removed.patch)"

in webkit 2.22.6 causes the issue.  This patch is not present in QS008 builds that use 2.22.5
We can make the QS009 build work correctly - by building webkit 2.22.6 without this patch. 

The details of this patch are as follows:

From: nganes961 <nambirajan_ganesan@comcast.com>
Date: Tue, 21 Jun 2022 11:54:51 +0000
Subject: [PATCH] Bring-back-the-compositor-buffer-that-was-removed

.../graphics/cairo/ImageBufferCairo.cpp | 55 +++++++++++++++++--
.../graphics/cairo/ImageBufferDataCairo.h | 6 ++
2 files changed, 56 insertions, 5 deletions

I can produce a debug log file if required - but the issue is not subtle - it is 100% reproducible and very easy to create.
1. Update llama device to QS009
2. start play.works application
3. Start food smash game
4. Advert plays. After it finishes screen goes black. The game screen does not appear as it should.

**Comment by magomez** [comment] 2022-08-30 12:33
@nrajan002c , is the page showing the error accesible? could you share the link?

I'll try to reproduce this with the rpi, but I'm afraid it's going to work properly. In that case, I'll prepare a patch with some logging for you to run the problematic scenario and send me the result back. Let's see if I can pinpoint the problem from that log.

**Comment by magomez** [comment] 2022-08-30 13:19
I found the food smash game in https://sky.play.works/service/apps/portal/index.html, but it doesn't show any add when launching.  I see the game logo with a loading page, then a spinner becomes visible for a while and then the main menu is shown, but no add.

**Comment by jacek-skiba-red** [comment] 2022-09-06 22:53
I checked cross-platform behavior:
* open https://sky.play.works/service/apps/portal/index.html
* start "lol omg" game
* video with ad is shown on chrome
* video with ad is not shown on WPE2.22 / WebKitGTK 2.36.6 / Firefox
    * on WPE2.22
        * we are not loading ad URL
        * settings.js file from 'lol omg' game has section 'adsSettings' which looks ok

**Comment by magomez** [comment] 2022-09-14 13:06
@nrajan002c could you, please, test the patch that I'm attaching and check whether it fixes the problem for that platform? Also, if you could also check whether it breaks any of your other platforms it would be awesome. It works for me on the hardware that I have, and I don't expect it to cause a regression, but just in case.

[916.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/9566521/916.patch.txt)

**Comment by magomez** [comment] 2022-10-11 14:54
@nrajan002c @jacek-skiba-red could you have a moment to test the patch that I attached, please?

**Comment by nrajan002c** [comment] 2022-11-16 14:17
Hi @magomez 
Sorry I missed to get notification of this github issue. 
Could you please provide 2.28 compatible patch (916.patch.txt) ?

**Comment by magomez** [comment] 2022-11-16 14:22
916.patch.txt is the one for 2.22.

This one is for 2.28
[969.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10022580/969.patch.txt)

**Comment by nrajan002c** [comment] 2022-11-25 13:58
@magomez We tried the above patches and did regression testing in different platforms.
We haven't faced any issues.

**Comment by magomez** [comment] 2022-11-25 14:02
> @magomez We tried the above patches and did regression testing in different platforms. We haven't faced any issues.

Great! I'll commit the change for 2.22 then. The one for 2.28 is still being tested in other platforms, but as soon as I get green flag I'll commit it as well.

**Comment by magomez** [comment] 2022-11-25 15:29
I've just pushed 1b5caf6c1c5cd48452113af94ebf2fa819bdae43 to the wpe-2.22 branch with the fix for that version.

As soon as I have confirmation in https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/969 that the equivalent fix for 2.28 doesn't cause regressions, I'll commit the fix to the wpe-2.28 branch as well.

**Comment by skarim248** [comment] 2022-12-09 15:16
Hi @magomez. We're planning to take 969.patch on wpe-2.28.1 (i.e. commit id: d35296c25ca9740d6f787735c596b5fe88f3a092), but there is some change in wpe-2.28.1 compare with wpe-2.28. Applied manually, please check this change and confirm if it is okay.   
[2-28-1.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10195946/2-28-1.patch.txt)

**Comment by magomez** [comment] 2022-12-12 10:39
@skarim248 you're missing a change that was done in 42f3a286a947f28e589055ef310914e3b35ac8fc , a couple of commits after the commit you're in. It adds a call to cairo_surface_flush that's necessary. If you cherry pick that commit then path 969 should apply cleanly. If you don't want to cherry pick that commit, you should modify your patch to add cairo_surface_flush(m_compositorSurface.get()); just before the call to glFlush() that your patch is adding.

**Comment by skarim248** [comment] 2022-12-12 11:40
Thanks @magomez

**Comment by magomez** [comment] 2023-01-10 14:35
@skarim248 , any news about this? can we close it?

**Comment by skarim248** [comment] 2023-01-12 03:47
Yes please. Changes has merged! 
Thanks for your support!

**Closed as completed** 2023-01-12 08:31 UTC
