### ISSUE TITLE
WPE 2.22 [Tv Francaise] Channel tile is blinking/jumping during navigation 

### ISSUE THREAD

**Issue by przemyslaw-gorszkowski-red** [Metrological/WebKitForWayland#832] opened 2022-04-15 12:12 UTC
When user is navigating in the right side in Tv Francaise application channel tile is blinking/jumping. 

When navigate left then tile is not blinking.

The problem can be observed:

https://user-images.githubusercontent.com/47318228/163569364-62fc1995-0aae-46e2-9696-a0341ad8fd49.mp4
 
It looks like the flickering is triggered by CSS change. A tile is represented by <a> node e.g.:
`
<a class="gpu item ng-scope" ng-repeat="channel in channels track by $index" ng-init="channelIndex = $index; channelKeyNavIndex = channelIndex" ng-class="{'activeChannel' : channelKeyNavIndex == activeChannelIndex}" pp-keynav="" pp-keynav-id="'channel-' + channelKeyNavIndex" pp-keynav-left="focusLeftChannel(channelKeyNavIndex)" pp-keynav-right="focusRightChannel(channelKeyNavIndex)" pp-keynav-down="gotoEpg(channelKeyNavIndex)" pp-keynav-enter="selectChannel(channelKeyNavIndex)" pp-keynav-active="channelIndex == currentChannelIndex">
`
A selected tile has two additional classes: activeChannel active. Both of them affect top attribute. There is also ng-animate class - application applies it on to-be-selected tile and removes after a very short while. In some cases during tile switch, the selected tile loses the CSS classes in sequence rather that in a single step - it is firstly stripped from activeChannel property and then cleared from active one a few hundreds milliseconds later. This may be the reason may be why tile jumps for while when it is unselected.

I believe exactly same application behavior can be observed on all browsers, including desktop Chrome and legacy WPE(2017 branch of WPE), it just works significantly faster there - on Chrome it is unnoticeable, while on legacy WPE(2017 branch of WPE) it is simply much faster. It has to be checked why WPE 2.22 seems to render the CSS modification slower.

**Comment by przemyslaw-gorszkowski-red** [comment] 2022-04-21 13:05
It seems that TVFrancaise has changed recently.  To workaround this problem you have to make a fake onesdk object before it is used by this app. To do this(by using webinspector) you have to find the place where onesdk.init() is called - I found it at line 7561 of the app.js. Please set a breakpoint there and start the app, when it reaches that breakpoint then call from console:

`window.onesdk = {init:function(){}, getUserGuid:function() { return new Promise(function(resolve) { return resolve(""); }) } , getDeviceInformation:function(){ return new Promise(function(resolve){ return resolve({middlewareVersion: "", country: "", firmwareVersion: "", deviceId: "", caSerialNumber: ""}); })}}`
 

After that select "Continue script execution" and the app should start.

**Comment by magomez** [comment] 2022-05-31 13:16
@przemyslaw-gorszkowski-red what's the URL I should use to reproduce this?

**Comment by przemyslaw-gorszkowski-red** [comment] 2022-06-01 09:27
@magomez : the link to application is: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:nl.peoplesplayground.app.ForeignTV

**Comment by magomez** [comment] 2022-06-10 14:47
I've been working on this, but I haven't found a solution yet. What I know so far is that it seems to be a 2.22 specific issue, cause it's not reproducible on 2.28.
There's some weird thing happening when a new element is selected and the previous one is deselected. I see that the app is not following exactly the same order in the operations that are done when scrolling left or right, and that's why on works fine and the other has the glitch. But the order of the operations should not matter and the result should be the same. But I haven't been able to pinpoint the origin of the problem yet, as it's quite tricky. I'm still working on it.

**Comment by rychem** [comment] 2022-06-27 10:20
@magomez would you please share any update on this issue?

**Comment by magomez** [comment] 2022-06-27 10:30
I haven't been able to work on it during the last days due to some high priority tasks, but I plan to return back to it as soon as possible. I'm sorry for the delay :(

**Comment by rychem** [comment] 2022-07-01 09:29
Thanks @magomez 
Do you maybe got already more clear view when investigation could be continued?

**Comment by magomez** [comment] 2022-07-20 14:24
Sorry for the delay folks. I've working on this during part of the last week and this one. The problem is that the styles code changed a lot from 2.22 to 2.28 (where it doesn't reproduce), so I cannot use 2.28 as a reference to see how the styles should be properly applied. So I have to fix it for the concrete 2.22 version, which is being very complicated because the styles code is huge and complex. So far I haven't been able to find a fix that doesn't break other rendering cases. And I'm getting more urgent tasks constantly, so I can't devote as much time as needed to this.

**Comment by woutermeek** [comment] 2022-08-02 14:43
@rychem as discussed in the call, please check internally whether it is acceptable to keep this bug in 2.22 since it is not reproducible in 2.28 and a lot of work to resolve in 2.22.

**Comment by rychem** [comment] 2022-08-07 19:56
@woutermeek after consultation with Apps Team stakeholders, issue was accepted for WPE2.22.
We can close the ticket as won't fix.

**Closed as not planned** 2022-08-17 08:15 UTC
