### ISSUE TITLE
WPE2.22 - requestAnimationFrame can starve out setTimeout timers

### ISSUE THREAD

**Issue by jakub-gocol-red** [Metrological/WebKitForWayland#796] opened 2022-03-01 08:54 UTC
On [euronews](https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.Euronews) application, when I try to open video, it often starts very late (sometimes even after 15-20s). This delay is not caused by buffering, but because source on video element is also set very late. I narrowed down the issue to requestAnimationFrame api, which causes setTimeout timers to not fire when they're supposed to. 

After clicking on video in euronews, two things are happening at once.
* application sets timer for setting source on video element. It looks a bit like this: setTimeout(()=>{video.src = "http://some.url/video.mp4"}, 100)
* application renders spinner that indicates loading of video. It's rendered on canvas with opengl calls. To schedule rendering function every frame (50 times per seconds), application uses requestAnimationFrame API.

Observed behaviour is that rendering function is executed 50 times per seconds and usually takes 19-20ms (so there is no much time for anything else), but timer which is supposed to fire in milliseconds, really is executed seconds after request (sometimes 1 second, sometimes 20 seconds).
In the browser, regular timer started with setTimeout is implemented in RunLoopGLib.cpp as timer with priority MainThreadSharedTimer (-60). RequestAnimationFrame also at some points ends up as timer in RunLoopGLib.cpp, but with DisplayRefreshMonitorTimer priority (-70)).
Because requestAnimationFrame timer has higher priority and uses up all procesor time, setTimeout timer is starved out.

I found similar issue in upstream webkit repository (https://github.com/WebKit/WebKit-http/commit/7eb5f68037fc9d6b0e2adb18d14ec8d34182a43f). They had similar issue when animations starved out other timeouts. It was fixed by lowering priority of DisplayRefreshMonitorTimer timer to lower value than MainThreadSharedTimer. But for some reason this fix was only implemented in WebKitGtk wariant (WebKitGtk and WpeWebKit have separate values of those priorities). In my opinion this solution is also wrong, because it just reverses the problem - with lots of work in setTimeout callbacks, requestAnimationFrame can be starved out. Instead DisplayRefreshMonitorTimer and LayerFlushTimer priorities should be set to -60.

NOTE: It doesn't seem right that WebKitGtk and WpeWebKit have different sets of priorities. It's not something that is platform dependent. Also variants of WebKit without glib don't have timer prioritization mechanism at all and they seem to work fine.

**Comment by jakub-gocol-red** [comment] 2022-03-02 13:30
I created pull request with proposed fix: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/798

**Comment by magomez** [comment] 2022-03-16 09:23
Thank you for your detailed analysis @jakub-gocol-red. It's true that WebKitGTK and WPE have different timeout priorities, but this is intended behavior, because WebKitGTK and WPE target different hardware: the former is mainly intended to be used on the desktop, where there's in general more resources and CPU power to use, while the latter is intended to be used on embedded systems with lower resources. The timer priorities used in WPE try to to achieve a better framerate in situations where the processing power is low.

I'm reluctant to accept your PR to change the priorities because the current values are a quite delicate balance, and modifying them can lead to undesired side effects (it may fix your issue, but may cause fails in other use cases). So I'd like to get more information about your problem and check other possible solutions before going that way.

I've been trying the problematic scenario on the rpi and I can't reproduce it. The video source is set almost immediately and the playback starts without delay.

From what you're describing, I imagine that you're using a hardware that's quite slow. Is it a single core processor? In a normal scenario, where the video mode is set to 60fps, requestAnimationFrame should be running 60 times per second, but you mention that it runs 50 times per second, which means that the hardware is not able to achieve those 60 fps when drawing a simple spinner with WebGL, which seems quite strange... a simple spinner should not be consuming all those resources.

In general, even with the current values of the timers, there's a moment during each frame where the main thread is waiting for another thread to finish the rendering, and during this time it's able to process those shared timers. That should be happening for your case as well. What comes to my mind is that your hardware has a single CPU core, or that it's quite slow and it's using nonCompositedWebGL for the view (which reduces the time waiting for the secondary thread).

Also, which platform are you running? Is it a Broadcom box?

**Comment by jakub-gocol-red** [comment] 2022-03-29 13:41
I checked it on different broadcom device (not rpi), which has 2 core CPU and animations are caped at 50fps. But the issue was easily reproduced on raspberry pi by my colleague (100% reproduction rate). It looked exactly the same on both devices. 

> it may fix your issue, but may cause fails in other use cases

The whole issue is that we don't have enough resources to execute everything fast enough and browser has to prioritize work. It can either decide that animations are more important (as in current implementation), but that leads to issues like this one. When it decides that animations are less important and regular javascript timers should have higher priority, it can lead to choppy animations, or even to complete stop. When we make those priorities equal, worst case scenario there will be fps drop when there is a lot of animations to execute and a lot of work done in javascript timer callbacks. But IHMO there is no other way around it. Either we will potentially slow down animations to make room for javascript timers (by decreasing their priority), or we will have beautiful animations, but with no javascript executed (as we do now). I think second option is worse.

**Comment by magomez** [comment] 2022-03-29 14:29
@jakub-gocol-red , would you be ok with adding an option to the build that allows switching between the 2 options? The current one and the one that works for you? That way we could cover all of the cases without introducing regressions to other users/platforms.

**Comment by magomez** [comment] 2022-03-29 15:19
@jakub-gocol-red can you apply this patch and build passing -DENABLE_FRAME_TIMERS_PRIORITY_REDUCTION=ON ? That should give you the priorities you need. When you confirm that it works, I'll commit it to the wpe-2.22 branch.

[add-option-to-reduce-frame-timers-priority.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8372838/add-option-to-reduce-frame-timers-priority.patch.txt)

**Comment by woutermeek** [comment] 2022-04-14 07:02
@jakub-gocol-red could you please check if this works for you?

**Comment by magomez** [comment] 2022-04-29 07:54
@jakub-gocol-red any feedback about this?

**Comment by jakub-gocol-red** [comment] 2022-05-05 08:11
@magomez yes, such solution works and would be acceptable if we don't want to touch timers priorities for all the other users.

**Comment by magomez** [comment] 2022-05-05 09:20
@jakub-gocol-red I've just pushed 25ae57b7a8cf00d093c8e3e9674a46d2e8eb005e to the wpe-2.22 branch. You can now build with -DENABLE_FRAME_TIMERS_PRIORITY_REDUCTION=ON in order to get the timer priorities you need for that platform. Please, verify that it works and close this if everything is ok.

**Comment by woutermeek** [comment] 2022-05-20 11:12
@jakub-gocol-red closing this issue, if there is an problem with the fix please re-open.

**Closed as completed by woutermeek** 2022-05-20 11:12 UTC
