### ISSUE TITLE
Partial Canvas not updated - wpe 2.38

### ISSUE THREAD

**Issue by jaroslaw-bojko-red** [Metrological/WebKitForWayland#1131] opened 2023-07-28 13:43 UTC
Hi!
After the upgrade to WPE webkit 2.38 we face the problem with canvas partial update.

The code below does not work:
		var imageWidth = 200;
		var imageHeight = 80;
		ctx.putImageData(imageData, 0, 0, imageWidth, imageHeight, imageWidth, imageHeight);
After executing putImageData the canvas remain the same.

On the other hand, the code:
		ctx.putImageData(imageData, 0, 0, 0, 0, imageWidth, imageHeight);

Works properly (please pay attention that the second putImageData is painted in top left corner, while the first is shifted by mageWidth, imageHeight. Any update that is not executed with 0,0 point is ignored.
Cairo library is in 1.16 version.

I created two TC to present the issue:
[canvas_bgra_nok.html.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12195083/canvas_bgra_nok.html.txt)
[canvas_bgra_ok.html.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12195085/canvas_bgra_ok.html.txt)

canvas_bgra_nok.html.txt - shows the problem
canvas_bgra_ok.html.txt - works fine on the device, the only change is putImageData arguments 

In Cairo 1.16 we also needed to fetch a fix from the master:
commit 99dc4bf4cedda6f8c71ce978a945b8f445d31105
Author: Heiko Lewin <hlewin@gmx.de>
Date:   Tue Jan 19 11:26:33 2021 +0000

    Fix device errors for GLESv2 contexts
    Ignore GLerrors when re-selecting a (possibly deleted) GLprogram

Without the commit on our new device ApolloV1+ the putImageData shows only a black screen. Nothing is painted, no matter is a partial or full canvas update. Additionally, this commit fixes the significant memory leak that we face in Euronews App.

Does anyone face similar problem with Cairo 1.16 and the 2.38 Webkit?

**Comment by magomez** [comment] 2023-08-01 17:34
I've just pushed bae1097314be36db5ec04e6e7f6cceb19db93c27 to the 2.38 branch, which should fix the putImageData issue. @jaroslaw-bojko-red, please verify that the fix works for you as well and close this if everything works fine.

I don't know why you should need to get any patch from master to make things work. It should work out of the box, at least I haven't seen this in any other device. Try the fix that I added without the cairo patch, just in case it's something that get fixed with it, despite I don't have high hopes. If the cairo patch is required... well, just keep it around for that platform, we can't do much more.

**Comment by jakub-gocol-red** [comment] 2023-08-03 10:12
I checked your change and it helped for test case from first comment.
But for us this whole issue started with timer on teletext that's not updating correctly (it updates every ~5s). With this patch it updates more or less every second, but spacing between updates is not even (it's visible on the [attached video](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/dcb9f725-e317-4404-aadf-e93eb07cf1ac
)).

It's working correctly with hardware acceleration disabled.

So this patch improves situation, but it's not 100% resolved.

**Comment by magomez** [comment] 2023-08-03 11:04
Is there any way I could have access to that teletext application? I would be way easier to debug it if I can reproduce the issue locally. If that's not possible, could you give more info about what's that application and how that update is being done? Is that a lightning application? or a normal HTML with a canvas? are just the timer numbers what's being updated? or the whole page? I understand that it uses setTimeout to update every second and then calls putImageData to overwrite the timer, is that it?

I expect a small update of the page like that will be faster with hw acceleration disabled, because in that case it's just a small memory copy. But with hw acceleration enabled it becomes more complex. That's why small canvases are not accelerated, as the performance would be worse.

**Comment by jakub-gocol-red** [comment] 2023-08-04 13:48
I asked around and this teletext application is closed source and not trivial to run (just opening url in the browser won't work). I'll prepare minimal test case that reproduces it.

**Comment by magomez** [comment] 2023-08-06 16:19
@jaroslaw-bojko-red can you test the patch that I'm attaching to check whether it improves the situation? Please apply it after the commit that a I previously pushed. The patch should make things a bit faster, maybe enough for the issue not to be perceived.

[1131.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12270009/1131.patch.txt)

**Comment by jakub-gocol-red** [comment] 2023-08-09 11:33
That patch is not working very well. I have either black screen or screen doesn't update. I checked it on both test cases from ticket description and on teletext app.

**Comment by magomez** [comment] 2023-11-16 11:24
I've added some changes to the acc canvas related to synchronization and how the frames are composed. @jakub-gocol-red could you check whether the teletext problem has improved at all? If the behavior is not better, I don't think there's much else that I can do.

**Comment by modeveci** [comment] 2024-02-27 12:31
@amol-virnodkar-infosys any update on this ticket?

**Comment by amol-virnodkar-infosys** [comment] 2024-03-11 10:54
We merged upstream changes and enabled 2d canvas, this helped to fix the issue. Now the issue is not reproducible. The time is updating properly every second in the teletext screen. Thanks.

**Comment by magomez** [comment] 2024-03-11 12:31
> We merged upstream changes and enabled 2d canvas, this helped to fix the issue. Now the issue is not reproducible. The time is updating properly every second in the teletext screen. Thanks.

Closing this then. Thanks!

**Closed as completed by magomez** 2024-03-11 12:31 UTC
Labels: wpe-2.38
