### ISSUE TITLE
[wpe-2.38] Incorrect rendering with flexbox layout

### ISSUE THREAD

**Issue by filipe-norte-red** [Metrological/WebKitForWayland#1417] opened 2024-10-16 08:59 UTC
The attached [index.zip](https://github.com/user-attachments/files/17392233/index.zip) contains an example page using flexbox layout where the content is not correctly rendered:

Expected:
![expected](https://github.com/user-attachments/assets/e007b0bf-21ba-418e-9ca7-3bd05fc9661a)

Actual:
![actual](https://github.com/user-attachments/assets/a66ac251-514b-4296-bcbe-ffb00a148295)

Removing the "flex-direction" or "justify-content" properties in the "menu-title-container" style, causes the content to be correctly rendered (in the later case the content will not be centered when compared to the "expected" result above).

The attached example page renders as expected on Chrome and Firefox.

Internal reference: LLAMA-14257

**Comment by pgorszkowski-igalia** [comment] 2024-10-17 05:42
The problem can also be reproduced on the latest WebKit. I will create an upstream report and investigate it there.

**Comment by pgorszkowski-igalia** [comment] 2024-10-23 18:00
Just some findings about this issue: so the main problem is when we have an embedded flexbox container inside other flexbox container and the main/outside flexbox container has `max-height` set to smaller value than the `height` value set in inside container, simple test case:
```
<html>
<head>
    <style type="text/css">
        .focusable-menu-item {
            width: 368px;
            height: 70px;
            max-height: 70px;

            color: #fff;

            display: flex;
            align-items: center;
            flex-direction: column;
        }

        .menu-title-container-focused {
            background: red;
        }

        .menu-title-container {
            display: flex;
            justify-content: center;
            flex-direction: column;

            width: 100%;
            height: 300px;

            text-align: center;
        }
    </style>
</head>
<body style="background-color:black">
        <div class="focusable-menu-item">
            <div class="menu-title-container menu-title-container-focused"><span style="font-size: 26px;">OPTION 1</span></div>
        </div>
</body>
</html>
```

The problem is seen only in case of `flex-direction: column/column-reverse` and `justify-content: center/space-around/space-evenly` for embedded container.
It seems that the `max-height` from the outside container is not taken into consideration when the final size(height) of the item is calculated.

I am still investigating the possible solutions without introducing regressions for other cases with flexboxes.

**Comment by pgorszkowski-igalia** [comment] 2024-10-24 10:08
The issue is reported in upstream: https://bugs.webkit.org/show_bug.cgi?id=282036

**Comment by pgorszkowski-igalia** [comment] 2024-11-02 10:03
I am working on the solution in upstream: https://github.com/WebKit/WebKit/pull/35859, The current draft and potential fix introduces regressions in other LayoutTests of FlexBox layouts so I need to find a different way to solve it.

**Comment by pgorszkowski-igalia** [comment] 2024-11-07 12:54
The fix in upstream is under review right now, but I don't know how long it would take to merge. There are no regressions in the existing layout tests. I tested it also with provided minimal test case and the original case from: https://cloud.rtl.it/hbbtv.rtl.it/skyq/index.html, it works there.
@filipe-norte-red: Can you use this change to check possible regressions with your internal test cases? The scope of testing should be flexbox layout. The branch of wpe-2.38 with my change: https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/3ce34e6f1b70e2d3a43d27423cd8df5684604b06

**Comment by filipe-norte-red** [comment] 2024-11-13 08:21
@pgorszkowski-igalia, I'll run the changes through some tests and apps to see if there are any obvious regressions and let you know

**Comment by filipe-norte-red** [comment] 2024-11-18 17:32
@pgorszkowski-igalia , I did some initial testing using several apps and some testc ases (although not specifically focused on flexbox) and have not observed any visible regressions so far.
We are still testing a bit further on other devices. Kindly bare with me a few more days for those results.
Thanks

**Comment by pgorszkowski-igalia** [comment] 2024-11-18 19:40
I also created a test on WPT (web-platform-tests) for this case to have it covered on other browsers too.

**Comment by filipe-norte-red** [comment] 2024-11-25 08:46
@pgorszkowski-igalia , no regressions were observed after further testing, so the change would seem to be good to be merged. Thank you!

**Comment by pgorszkowski-igalia** [comment] 2024-11-26 09:04
PR created: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1431

**Comment by pgorszkowski-igalia** [comment] 2024-11-27 06:03
The PR https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1431 is merged, so I close this issue.

**Closed as completed by pgorszkowski-igalia** 2024-11-27 06:03 UTC
Labels: wpe-2.38
