### ISSUE TITLE
[WPE 2.38] Black blink before background image is loading in oneplus app

### ISSUE THREAD

**Issue by jakub-gocol-red** [Metrological/WebKitForWayland#1207] opened 2023-10-05 09:01 UTC
### Reproduction steps
1. Open oneplus app (https://stv.oneplus.ch/home/hero/1649428)
2. If you receive 403, switch user agent to `Mozilla/5.0 (Linux armv7l) AppleWebKit/602.1.28+ (KHTML, like Gecko) Version/9.1 Safari/601.5.17 HZN/5.07 (MN=VIP7002W-DEV;PC=APPSTB;FV=VIP7002W-wpe-dbg-06.02-000-aa-AL-20230831210000-un000;)`
3. Scroll thumbnails left/right and observe background image

### Expected behaviour
Background is switched immediately, without black screen, as on wpe2.22

### Actual behaviour
There's black background when switching from old to new image

### Notes
Video with comparison of wpe 2.22 and 2.38

https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/de634b45-6924-4e3b-8028-af3c506b98a6

App doesn't require credentials for reproduction.

**Comment by magomez** [comment] 2023-12-08 09:41
I haven't looked into it, but the black frame is probably coming from the async decoding of large images, which paints a transparent placeholder while the image is being decoded, and paints the images when they are available.

**Comment by magomez** [comment] 2024-02-07 13:58
@jakub-gocol-red can you give this patch a test? It disables async decoding of large images, which removes the problem for me on the rpi. This is disabled in 2.22 and that's probably because the black blink doesn't happen there.

[disable-async-decoding-for-large-images.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/14194738/disable-async-decoding-for-large-images.patch.txt)

**Comment by janani-balasubramanian-infosys** [comment] 2024-02-13 08:58
@magomez The black blink issue is not seen after making the changes from the patch file attached.
The images are loading without black screen pop-up.

**Comment by magomez** [comment] 2024-02-14 13:35
I've just pushed the fix to the wpe-2.38 branch. Please verify that the problem is fixed and close this. Thanks!

**Comment by magomez** [comment] 2024-02-15 11:04
> I've just pushed the fix to the wpe-2.38 branch. Please verify that the problem is fixed and close this. Thanks!

On second thought, the change is the same that was already verified, so I'll close this myself. Please reopen if for some reason the problem persists.

**Closed as completed by magomez** 2024-02-15 11:04 UTC
Labels: wpe-2.38
