### ISSUE TITLE
Buffering rate algorithm issues

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#928] opened 2022-08-24 12:03 UTC
There's an application which loads data into source buffers and waits for `readyState > 3` (that is, HaveEnoughData) to start playing. The problem is, `monitorBufferingRate()` function is being called at very different intervals and thus the moving average calculation is very inaccurate. It results in `readyState` being at `3` for very long while (or for ever) in some cases.
If the `readyState` is `<=3` for a longer while, the application calls `seek(0.1)` as it sometimes results in proper `readyState` calculation.

For slight improvement, the https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/927 may be used. However, it does not resolve the issue entirely.

Link to app: https://sky.joinhighbrow.com/sky/app/4b983f1f-cc7a-40c9-8584-87bbe059ebbf/
To reproduce an issue it's enough to play first listed asset. If it loads correctly, then one can use right arrow and hit enter to move to next asset - the buffering for 10+ seconds means the issue is likely there.

- The issue can be observed e.g. on WPE WebKit 2.28 (MiniBrowser).
- I've seen this issue also on Web 3.36.4 (WebKitGTK 2.36.6) although it froze after a short while.
- I've tried Eolie 0.9.101 but the freeze of asset loading was immediate and thus I could not test it further.
- ~~I've also tried recent Safari on Mac and the problem is not visible there for some reason - the code in WebKit `master` suggest there were no changes to the algorithm and the way we call `monitorBufferingRate()`~~
- I've tried Safari 15.1 on Mac again and this time I've reproduced the problem (please note the reproduction rate may depend on internet connection bandwidth), see JS console log: 
<img width="1423" alt="Zrzut ekranu 2022-08-25 o 13 18 42" src="https://user-images.githubusercontent.com/1207385/186652388-a2838f0a-a220-4324-9275-44d0626823ba.png">

**Comment by eocanha** [comment] 2022-11-09 18:38
I wasn't exactly able to reproduce the issue exactly as described (with the https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/50bc3a06555af5c4643e35e980bc7ec708d0e690 commit from  PR https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/927 applied), but did notice big periods without calls to `monitorSourceBuffers()`, and that causes big update intervals and big jumps in `m_averageBufferRate` by forcing the network bandwidth assigned to the device (a Raspberry Pi 3) between 0.2 and 2 Mbps.

`MediaSource::monitorSourceBuffers()` is only called in `completeSeek()`, `finishSeek()`, `playbackProgressTimeFired()` and `sourceBufferPrivateAppendComplete()`. `playbackProgressTimerFired()` should avoid long delays in updates. I found that when the player isn't playing (because of prebuffering, or because of rebuffering after the network became slow (HaveCurrentData reached) and the player autopaused. Finding a way to call `monitorSourceBuffers()` periodically even when the player isn't playing should improve things. I'm currently exploring this line of work.

**Comment by Scony** [comment] 2022-11-10 17:18
That was my observations as well. I hope you'll find a way to ensure `monitorSourceBuffers()` is being called at equal intervals despite the state the player is in.

**Comment by eocanha** [comment] 2022-11-11 10:54
I've finished implementing periodic calls (see my [eocanha-debug-127](https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/eocanha/eocanha-debug-127) draft branch). However, I noticed that under some circumstances (after a low to high forced network bandwidth change) the high update intervals keep happening, even though the timer is enabled to be triggered every second. I suspect that something might be stalling the main thread. I need to find what it is.

**Comment by eocanha** [comment] 2022-11-22 21:14
The few reproductions I managed to get during the last week showed that [playbackPosition()](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.28/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L1434) might be the cause of the delay (although I can't be completely sure).

However, I haven't been able to reproduce the stalls in the last days. I've updated the [eocanha-debug-127](https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/eocanha/eocanha-debug-127) branch with extra logs to try analyze the time taken by the duration query.

@Scony, would you please run that branch and get some logs for me in case you're able to reproduce the issue again?

**Comment by Scony** [comment] 2022-11-23 14:12
@eocanha  sure: 
[console.log.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10076255/console.log.gz)

Nudging mechanism kicks in, and I can see some invalid `monitorBufferingRate` intervals

**Comment by eocanha** [comment] 2022-11-25 17:48
From those logs and from the code, I've been able to detect a problem with the way in which `m_timeOfBufferingMonitor` is initialized in SourceBuffer. It's [initialized to the SourceBuffer creation time](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/6a0c6195af27694e09bb57933e91ce1239591d55/Source/WebCore/Modules/mediasource/SourceBuffer.cpp#L147), so if the call to [`monitorBufferingRate()`](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/6a0c6195af27694e09bb57933e91ce1239591d55/Source/WebCore/Modules/mediasource/SourceBuffer.cpp#L2273) takes too much to happen for whatever reason, the computed interval is already going to be too big and generate an artificially low [`m_averageBufferRate`](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/6a0c6195af27694e09bb57933e91ce1239591d55/Source/WebCore/Modules/mediasource/SourceBuffer.cpp#L2282).

To mitigate this, I've added code to initialize `m_timeOfBufferingMonitor` to zero, detect that special value in `monitorBufferingRate()` and skip the first time that the rate computation is done (just assigning the "now" time to `m_timeOfBufferingMonitor`, so when the next update is done, the interval is most realistic).

This may have solved part of the issue. The other part is that sometimes (because reproducing this is really inconsistent), I've observed unusually long intervals that shouldn't be there, and I can't really tell why they are caused. I keep thinking that the main thread may be stalled in some way, but I really have no way to find the cause (I've tried multiple ways to autodetect those stalls, autopause the WebProcess and attach gdb, without successful results). The only thing I know is that duration queries (my initial suspect) don't seem to be the cause of those mysterious main thread stalls. This is what I got in the logs regarding the mysterious stall (there should be "tick" lines every second, but look at the jump in gst log timestamps from 30.24 to 41.04):

```
0:00:29.359613478  2092   0x743920 DEBUG              webkitmse HTMLMediaElement.cpp:3956:playbackProgressTimerFired: tick: monitorSourceBuffers()
0:00:30.248863113  2092   0x855e18 DEBUG         webkitmediasrc platform/graphics/gstreamer/mse/WebKitMediaSourceGStreamer.cpp:420:webKitMediaSrcQueryWithParent:<source> duration query in format bytes
0:00:41.047855713  2092   0x743920 TRACE      webkitmediaplayer platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:651:currentMediaTime:<media-player-1> seeking: false, seekTime: {-1/1 = NaN, invalid}
0:00:41.047905036  2092   0x743920 TRACE      webkitmediaplayer platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:1436:playbackPosition:<media-player-1> isEndReached: false, seeking: false, seekTime: {-1/1 = NaN, invalid}
0:00:41.047939046  2092   0x743920 DEBUG      webkitmediaplayer platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:1456:playbackPosition: Query (before)
0:00:41.048634671  2092   0x743920 DEBUG      webkitmediaplayer platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:1458:playbackPosition: Query (after)
0:00:41.048730401  2092   0x743920 TRACE      webkitmediaplayer platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:1466:playbackPosition:<media-player-1> Position 0:00:20.173366666, canFallBackToLastFinishedSeekPosition: false
```

I've updated the [eocanha-debug-127](https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/eocanha/eocanha-debug-127) branch with my latest changes for you to try again.

**Comment by Scony** [comment] 2022-11-28 10:44
Looks like `m_timeOfBufferingMonitor` initialization fix helps a lot - it's much harder to reproduce the issue.
Yet the question of mysterious stalls remains.
[console.3.log.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10102880/console.3.log.gz)
[console.2.log.gz](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10102882/console.2.log.gz)

**Comment by eocanha** [comment] 2023-02-21 18:04
I've been analyzing the new provided logs and I see that the readyState changes are caused by m_averageBufferRate being lower than 1. However, all the intervals between calls to monitorBufferingRate() are lower than 1 sec. My interpretation of this data is that there might be some actual network shortage that is causing a low buffering rate and legitimately triggering the readyState changes from HaveEnoughData to HaveFutureData.

Might that be triggering some pausing code on the JavaScript page?

**Comment by Scony** [comment] 2023-02-28 11:10
I don't think so, the results are consistent across various QA teams from various locations with various network connections.

**Comment by eocanha** [comment] 2023-03-02 16:46
By now I'm trying to upstream https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/5adf7f109284d3d9e042782c376b94de0f95ef19 as https://bugs.webkit.org/show_bug.cgi?id=253074 / https://github.com/WebKit/WebKit/pull/10793.

**Comment by eocanha** [comment] 2023-03-07 20:12
Landed upstream as https://commits.webkit.org/261328@main. Backported to wpe-2.28 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/54651c3b98a7907b72bd8b613616e58d40ca7c5a and to wpe-2.36 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/fa9fc09899812f48a2432f1d7a1085567da20ccc.

**Comment by modeveci** [comment] 2023-09-25 14:48
@eocanha is this resolved? If so, can we close this ticket? Thank you!

**Comment by eocanha** [comment] 2023-09-25 18:15
No, not completely resolved yet. At this point, ["it's much harder to reproduce the issue"](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/928#issuecomment-1328868829), but there are still some cases where the problem remains. Still, debugging those cases is going to require a considerable amount of effort, because the last time I tried to debug the problem I used all the tricks I could and ran out of ideas. Maybe @Scony can tell if the current solution is "good enough" or if this this issue really deserves the extra debugging.

**Comment by Scony** [comment] 2023-09-26 08:32
@eocanha actually the highbrow app made some workarounds on their end to address that, so the issue is technically not having a real world use case. Therefore we can de-prioritize it. Nevertheless the issue is still there - I'm going to prepare some small application for reproducing this issue easily and then we can try making some progress.

**Comment by rawoul** [comment] 2023-09-26 09:49
FYI we also see the current algorithm is broken is multiple cases with AppleTV:
- When stream is paused for some time, the average buffering rate can drop below 0, so canPlayThroughRange will always return true
- During initial preroll, the player will push a "sufficient" amount of data (a fixed amount of time, vs pushing until getting a QuotaExceeded error) for both audio and video streams. If one of the streams is fed a little late compared to the other, in the meantime the average buffering rate of the other streams will drop. You can get in a state where all streams have prerolled data, but not all streams have canPlayThroughRange returning true, preventing switching to the HAVE_ENOUGH_DATA state.

I don't think an algorithm based on elapsed time can work. I've implemented the same algorithm as Firefox to make it work (canPlayThroughRange returns true when 3s of data is buffered), and it works fine: https://github.com/rawoul/WebKit/commit/d836c3a263066b0c9810d3a313b75390c61741b6

**Comment by eocanha** [comment] 2023-09-26 10:38
@Scony, can you try @rawoul's patch to see if it solves the problem for you (I don't know if you both work on the same team). If that's the case, we could try to upstream that patch (in the best case) or to apply it downstream in the general case as an exception.

**Comment by Scony** [comment] 2023-09-26 13:41
@eocanha I'll give it a try, sure.

**Comment by eocanha** [comment] 2023-11-06 15:22
Any feedback about this? Are things improving? Is this issue still relevant?

**Comment by Scony** [comment] 2023-11-06 20:24
@eocanha I've been pretty overwhelmed by higher-priority tasks the last few months, so overall I probably spent 1 hour total on developing a test case to reproduce it easily. I got it ~75% finished for weeks now but I'll try my best to finish it in the upcoming couple of weeks. Once I have a test case, I'll compare the current implementation with the one from @rawoul

**Comment by Scony** [comment] 2023-11-14 15:38
@eocanha I finally managed to give this issue some harder push.

I've finished preparing test cases:

1. (open for debate) https://cpetestutility.stb.r53.xcal.tv/webkit/tests/LLAMA-7401_mse_canplaythrough_estimation_on_startup.html where the data is added before starting to play in which case (IMO) webkit should yield `canplaythrough` event as we have enough data and the playback is not even progressing
2. https://cpetestutility.stb.r53.xcal.tv/webkit/tests/LLAMA-7401_mse_canplaythrough_estimation_during_playback.html where the negative value of `m_averageBufferRate` is reproduced. In this test case, the playback won't progress after buffering.

I've tested both TCs on arm32 platform and on local, x86-64 build.

Moreover, I've tested both cases with https://github.com/rawoul/WebKit/commit/d836c3a263066b0c9810d3a313b75390c61741b6 (@rawoul fix) and both test cases work as expected in that case.

**Comment by eocanha** [comment] 2023-11-15 18:39
> Moreover, I've tested both cases with [rawoul/WebKit@d836c3a](https://github.com/rawoul/WebKit/commit/d836c3a263066b0c9810d3a313b75390c61741b6) (@rawoul fix) and both test cases work as expected in that case.

"As expected" means that the issue isn't reproduced and that the patch is good to fix it, right?

**Comment by Scony** [comment] 2023-11-15 19:25
@eocanha yes, right.

**Comment by eocanha** [comment] 2023-11-17 13:36
A version of Rawoul's patch has been submitted upstream for review as https://bugs.webkit.org/show_bug.cgi?id=265023 / https://github.com/WebKit/WebKit/pull/20663.

**Comment by Scony** [comment] 2023-11-17 16:29
Thanks @eocanha

**Comment by eocanha** [comment] 2024-01-09 20:28
https://bugs.webkit.org/show_bug.cgi?id=265023 / https://github.com/WebKit/WebKit/pull/20663 has landed upstream as 
https://github.com/WebKit/WebKit/commit/c55cda1034c1186dcc545119f1e5f108b86a5159 and has been backported to wpe-2.28 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/45bd60508487203bbde491111ca894af3276b80b, to wpe-2.38 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/98943f6d72667190113432f8f55295e18adf46df, and to wpe-2.42 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/e73217bb5f94440f6724b3358da1c72d75ebc05b.
Closing issue.

**Closed as completed by eocanha** 2024-01-09 20:28 UTC
Labels: wpe-2.28, upstream, wpe-2.38

**Comment by Scony** [comment] 2024-01-09 21:04
Perfect! Thank you.
