### ISSUE TITLE
current impl. of progressive playback START is nondeterministic in time domain

### ISSUE THREAD

**Issue by ghost** [Metrological/WebKitForWayland#755] opened 2021-12-07 07:47 UTC
Impl. in MediaPlayerPrivateGStreamer.cpp (none MSE path) monitors buffering level of GstQueue2/DownloadBuffer by
GST_MESSAGE_BUFFERING message parsing, if 100% fill level is reached (of complete stream downloaded) GST pipeline is switched to PLAYING. Because both of those elements generate GST_MESSAGE_BUFFERING based on their current fill level - information in message is not monotonic (oscillats). Moreover this information can not be used to impl. deterministic Time-To-Play requirement becuase its "byte-nature". Demuxed data which has PTS and DUR per media sample is needed to correctly estimate amount of buffered data in time domain (preferably from data pushed into decoder). This can be done by GST probes attached on audio/video decoder sink pads.
Or at least after all buffering elements like multiqueue.

**Comment by ghost** [comment] 2022-01-06 11:14
Please see following tests results with Metro App:
https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.Euronews

Testing was done on: Raspberry Pi 3 B+,
with reference image: rdk-generic-reference-image-2021-11-23-raspberrypi-rdk-hybrid-generic.rpi-sdimg


try | loading time
-- | --
1 | ~5 s
2 | ~8 s
3 | ~16 s
4 | ~1 s
5 | ~1 s
6 | ~2 s
7 | ~7 s
8 | ~12 s
9 | ~2 s
10 | ~23 s

More information is available at: https://jira.rdkcentral.com/jira/browse/RDK-503

**Comment by eocanha** [comment] 2022-01-24 18:05
I don't have access to the RDK-503 ticket nor to the RDK reference image at this moment (I usually work on images generated from [this buildroot](https://github.com/WebPlatformForEmbedded/buildroot)). I would need some additional information in order to understand properly the problem you describe:

Is the image you're using based on [wpe-2.22](https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/wpe-2.22) or [wpe-2.28](https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/wpe-2.28)?

If it's the former, and considering that the test case you linked doesn't exercise the video.buffered() API, I understand that your issue is about how buffering affects the readyState management, and therefore the time it takes until the video reaches the PLAYING state.

Are you enabling disk buffering (so GstDownloadBuffer is used) or disabling it (so GstQueue2 is used) in your specific WPEFramework setup? I ask about this to know where to focus my debugging on.

Assuming that you have it disabled and GstQueue2 is used, the only thing I can say by now is that, under such circumstances, buffering ([m_buffering](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L1563)) is used to decide when to change the readyState to up to [HAVE_ENOUGH_DATA](https://html.spec.whatwg.org/multipage/media.html#dom-media-have_enough_data) (a state "good enough" to guarantee playback for a while).

I don't exactly understand the purpose of you comment about implementing Time-To-Play requirements. I'm not currently aware of any API for JS apps to query or estimate how much time is still remaining until the readyState reaches HAVE_ENOUGH_DATA and the video goes to play (with guarantees of keeping up with the player data consumption rate without immediately stalling because of lack of data). The time until that state is reached only depends on the network conditions. Are you sure that the network conditions have been good all the times you tried to measure the Time-To-Play?

**Comment by ghost** [comment] 2022-02-01 09:39
Hi,

> Is the image you're using based on wpe-2.22 or wpe-2.28?

wpe-2.22

> I understand that your issue is about how buffering affects the readyState management, and therefore the time it takes until the video reaches the PLAYING state.

yes

> Are you enabling disk buffering (so GstDownloadBuffer is used) or disabling it (so GstQueue2 is used) in your specific WPEFramework setup? I ask about this to know where to focus my debugging on.

GstQueue2

> I don't exactly understand the purpose of you comment about implementing Time-To-Play requirements.

In comercial products you usually would like to guarantee such parameters (under the assumptions that network conditions are met).

>The time until that state is reached only depends on the network conditions. Are you sure that the network conditions have been good all the times you tried to measure the Time-To-Play?

No. Please see attached pipeline diagram. When GstQueue2 is being pumped in by WebKitWebSrc from network its also being pumped out by GstQtDemux (or equivalent element) from its "src pad" side. So GstQueue2 fill level depends on timing of data consumption rate of "buffering elements" on its "src pad" side. It fluctuates - depending on different stream/HW parameters.
Yes - after pipeline is filled playback is started but there is no time-domain control over playback start.

![PAUSED_PLAYING](https://user-images.githubusercontent.com/32842038/151943851-0718d93a-68c4-462b-85d1-2f5e0eab6be0.png)
.

**Comment by eocanha** [comment] 2022-02-02 14:29
I'm starting to see the problem here:

We usually do most of our user tests and debugging using a Raspberry Pi as reference system. In a RPI, the OMX decoder has a limited number of available buffers to place decoded video frames. This means that the pipeline "fills" (prerolls) very quickly, so the buffers quickly accumulate and fill the GstQueue2, reaching the needed buffering levels and providing a quick playback start.

However, on Broadcom Nexus systems the filter/decoder/sink (the Nexus system itself) has large internal buffers, "sucking" lots of buffers from the demuxer before Nexus saturates and the GstQueue2 really starts to increase its buffering level.

I can't come up with an easy solution, because what happens when the buffers enter the vidfilter/audfilter is basically out of our control (from the player and GStreamer perspective). Maybe there's some way to ask Nexus about its internal buffering levels and use that as the source of buffering measurements instead of the GstQueue2. I would need to think deeper about the topic.

**Comment by ghost** [comment] 2022-02-04 09:36
Hi,

Yes, this is exactly what is the problem. The worst is that fill level is highly depends on thread scheduling (oscillations).

Current impl. is not "customizable" in this respect.

One of the "semi-general" solution might be to put GST probes on sink pad of element which is located after multiqueue (~decoder), or implement interface to accept such a probe (which vendor can place where it is needed). Then each buffer can be inspected (PTS+DUR) and some threasholds might be established (different HW can use custom values here). Or even more general approach can be taken by refactoring out "decision making code" into separate class, which can by customized by vendors without modifying common code.

**Comment by eocanha** [comment] 2022-02-15 20:04
I've coded a [specific solution](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/14f712084b349ab70e87352d73dc02ee42c1a99e) for systems using Broadcom Nexus in the top of branch https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/eocanha/eocanha-114. Let me know if it would work for your specific case.

**Comment by rychem** [comment] 2022-02-16 15:05
Hi Enrique,
Thanks. We will validate the patch and come back with outcome

**Comment by ghost** [comment] 2022-02-18 11:56
@eocanha thanks for the patch.
We have some preliminary results which should good improvements.
We would like to share our final feedback but we need more time to do the correct validation.
We detected another issue which interfers with current one and impacts time-to-play (related to Euronews animation on playback start). This issue needs to be solved to get final outcome. Hopefully mid of next week is realistic.
Thanks for support.

**Comment by eocanha** [comment] 2022-02-21 17:50
There are some relevant comments in https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/14f712084b349ab70e87352d73dc02ee42c1a99e
Mentioning them so they get linked from this issue.

**Comment by jakub-gocol-red** [comment] 2022-03-29 13:10
I did a bunch of testing and it looks like [15f7120](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/14f712084b349ab70e87352d73dc02ee42c1a99e) fixes nondeterministic playback start.
Additionally there is separate issue with starved out timers which is reported here: https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/796 (with proposed patch).

With both those patches applied, euronews is fast and usable. On fast internet connection video starts in around 1 second, on slower connection it starts in few seconds at most, 100% reproducibly.

**Comment by rychem** [comment] 2022-03-29 13:33
Thanks Jakub.
@eocanha ticket can be closed. Many thanks for your help.

**Comment by eocanha** [comment] 2022-03-29 15:48
Ok. That commit now corresponds to https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/8c29ea2a71ecc9f63a6d95f2684563c495b22f8d in the updated branch. I'm going to push only that one to wpe-2.22 and when https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/792 is in a good enough state, I'll also push the other fixes (current-level-bytes, multiqueue content, pause when buffer empty).

**Comment by eocanha** [comment] 2022-03-29 15:57
Committed to https://github.com/WebPlatformForEmbedded/WPEWebKit/tree/wpe-2.22 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/0aa355cbca7375ba6258ba3b81fde465f6626a0c

Closing issue.

**Closed as completed by eocanha** 2022-03-29 15:57 UTC
