### ISSUE TITLE
[WPE-2.38] Background graphics are not rendering correctly with 2dcanvas enabled

### ISSUE THREAD

**Issue by jacek-skiba-red** [Metrological/WebKitForWayland#1175] opened 2023-09-12 13:21 UTC
On WPE 2.38 we see rendering issues in ANWB app: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.ANWB

Issue is reproducing on WPE 2.38 on Broadcom chip with VideoCore VI (this is our only platform on which we are integrating 2.38).
App is using lightning in version 2.4.0.

App renders correctly in:
* WPE 2.38 with disabled 2dcanvas on Brcm device
* WPE 2.38 build on Ubuntu
* WPE 2.22 with 2dcanvas enabled on Brcm device
* gnome web (based on webkitgtk 2.28.4)
* chrome

![anwb](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/42027818/09149957-b3dd-43d8-9fca-a8661ca2a77f)

We know that Lightning framework is using canvas for font rendering. In this context, lightning also is using canvas for background images?

**Comment by magomez** [comment] 2023-10-19 14:27
It seems that in this case Lightning is indeed using a canvas to render the content of the map. As the content is big, the canvas gets accelerated, and that seems to be causing the issue. One question, are you using nonCompositedWebGL when running that application?

**Comment by jacek-skiba-red** [comment] 2023-10-31 13:41
We are not using nonCompositedWebGL for that scenario (in general all our HTML5 and Lightning apps are running on one config which don't use nonCompositedWebGL).

Issue may be related to nonCompositedWebGL, because on Broadcom based Video Accelerator m393 issue was not seen (where app was running on LightningApp.json config, with noncompositedwebgl set to true).

**Comment by magomez** [comment] 2023-11-14 14:25
I've just pushed a couple of commits that restrict the usage of the accelerated canvas. This should avoid that the canvases used by lightning applications are accelerated, thus removing this issue. @jacek-skiba-red could you update and check whether this is fixed, please?

**Comment by magomez** [comment] 2023-11-28 09:19
WebGL can't use accelerated canvases now so this situation is not reproducible anymore. Closing.

**Closed as completed by magomez** 2023-11-28 09:19 UTC
Labels: wpe-2.38
