### ISSUE TITLE
WPE 2.22 - Network requests cannot be resolved after network change

### ISSUE THREAD

**Issue by maciej-kolanski-red** [Metrological/WebKitForWayland#785] opened 2022-02-10 09:47 UTC
Clone of RDK-511

**Reproduction steps**
1. Start any application (preferably Lightning: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.CNN)
2. Stop the application - navigate to URL used when browser is moved to the background.(https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot or even about:blank).
3. Change network - from ethernet to WiFi or vice versa.
4. Start the same application

**Expected result**
Application starts normally

**Actual result**
Application does not start, only black (or loading) screen is visible. 

**Logs**
Logs from 7218c brcmrefboard with wpe-webkit 2.22.3:
[network_change.log](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8039903/network_change.log)

Firstly CNN application is loaded, then it is stopped by navigation to the `#boot`:

```
Feb 09 14:16:22 brcm972180hbc-refboard-dunfell /usr/bin/WPEFramework[3179]: [Wed, 09 Feb 2022 14:16:22 ]:[WebKitBrowser.cpp:273]: Information: URLChanged: { "url": "https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.CNN", "loaded": true }
[... Plenty of SoupMessages requested and finished succesfully ...]
Feb 09 14:16:43 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 28 (0x1c4278), SoupSocket 5 (0x1c7e28)
Feb 09 14:16:43 brcm972180hbc-refboard-dunfell WPEFramework[4163]: < Soup-Debug: SoupMessage 28 (0x1c4278)
Feb 09 14:16:43 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 29 (0x1c41f8), SoupSocket 10 (0x1c84e0)
Feb 09 14:16:43 brcm972180hbc-refboard-dunfell WPEFramework[4163]: < Soup-Debug: SoupMessage 29 (0x1c41f8)
Feb 09 14:16:45 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 30 (0x1c45f8), SoupSocket 10 (0x1c84e0)
Feb 09 14:16:45 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 31 (0x1c4478), SoupSocket 3 (0x1c7d48)
Feb 09 14:16:45 brcm972180hbc-refboard-dunfell WPEFramework[4163]: < Soup-Debug: SoupMessage 31 (0x1c4478)
Feb 09 14:16:45 brcm972180hbc-refboard-dunfell WPEFramework[4163]: < Soup-Debug: SoupMessage 30 (0x1c45f8)
Feb 09 14:17:01 brcm972180hbc-refboard-dunfell /usr/bin/WPEFramework[3179]: [Wed, 09 Feb 2022 14:17:01 ]:[WebKitBrowser.cpp:273]: Information: URLChanged: { "url": "https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#boot", "loaded": false }
Feb 09 14:17:02 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 32 (0x1c43f8), SoupSocket 11 (0x1c8550)
Feb 09 14:17:02 brcm972180hbc-refboard-dunfell WPEFramework[4163]: < Soup-Debug: SoupMessage 32 (0x1c43f8)
Feb 09 14:17:02 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 33 (0x1c44f8), SoupSocket 11 (0x1c8550)
Feb 09 14:17:02 brcm972180hbc-refboard-dunfell WPEFramework[4163]: < Soup-Debug: SoupMessage 33 (0x1c44f8)
```

Then network is changed from eth to wifi:
```
Feb 09 14:17:08 brcm972180hbc-refboard-dunfell kernel: bcmgenet 8f00000.ethernet eth0: Link is Down
Feb 09 14:17:19 brcm972180hbc-refboard-dunfell kernel: [wlan0] Connecting with a4:91:b1:86:e0:b2 ssid "WiFi-2.4-7121", len (13) channels:40 
```
Then CNN tries to start once again:
```
Feb 09 14:18:27 brcm972180hbc-refboard-dunfell /usr/bin/WPEFramework[3179]: [Wed, 09 Feb 2022 14:18:27 ]:[WebKitBrowser.cpp:273]: Information: URLChanged: { "url": "https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.CNN", "loaded": false }
Feb 09 14:18:27 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > GET /proxy?url=https://services.cnn.com/newsgraph/search/topicLabel_exact:united%20states/language:en/rows:30/type:video/start:0/lastPublishDate,desc?api_key=zn2cp943gzffppt589mu525e HTTP/1.1
Feb 09 14:18:27 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 34 (0x1c4578), SoupSocket 10 (0x1c84e0)
Feb 09 14:18:27 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > GET /?platform=eos&customer=liberty&country=nl&household=b9ce1c604dcb19a3227159c0cd590f76af585a1ff8fe902ed2cbfe7af7fb7599&session=7ab99e5ac2bc71f08987ac927fc10605029c6f7024b967b515ff935adc187716&id=com.metrological.app.CNN&event=load&type=app HTTP/1.1
Feb 09 14:18:27 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 35 (0x1c44f8), SoupSocket 11 (0x1c8550)
Feb 09 14:18:33 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > GET /?platform=eos&customer=liberty&country=nl&household=b9ce1c604dcb19a3227159c0cd590f76af585a1ff8fe902ed2cbfe7af7fb7599&session=7ab99e5ac2bc71f08987ac927fc10605029c6f7024b967b515ff935adc187716&id=com.metrological.app.CNN&event=open&type=app HTTP/1.1
Feb 09 14:18:33 brcm972180hbc-refboard-dunfell WPEFramework[4163]: > Soup-Debug: SoupSessionAsync 1 (0x690c8), SoupMessage 36 (0x1c43f8), SoupSocket 12 (0x1c85c0)
Feb 09 14:18:33 brcm972180hbc-refboard-dunfell WPEFramework[4163]: < Soup-Debug: SoupMessage 36 (0x1c43f8)
```
Only this time  SoupMessages 34 and 35 do not resolve, while SoupMessage 36 resolves just fine, so the network is available. Noticeable difference is that the unresolved requests use SoupSocket 10 and 11, which were both initiated before the network change.

**Additional information**
It looks like internally libsoup creates sockets and tries to keep them alive for the sake of incoming request to the same host - though it also depends on the server side, but surely it is the case for http://cdn.metrological.com/lightning/maf/v2.6.2-47d60c2/maf_es5.js. It works just fine, unless the network change occurs in the meantime. In such case, libsoup does not drop the active connection automatically - it can be even reproduced with standalone latest libsoup. It looks like WebKit does not trigger the libsoup's connections reset as well, which I believe is the problem here.

What is more, hanged network request will literally never resolve, unless the original network interface is restored. This happens because [timeout](https://libsoup.org/libsoup-2.4/SoupSession.html#SoupSession--timeout) value is default=0.

**Workaround**
Set `SOUP_MESSAGE_NEW_CONNECTION` for each libsoup message - effectively disables reusing of sockets.

**Comment by rychem** [comment] 2022-02-10 11:10
@woutermeek the issue mirrorred from RDK-511

**Comment by magomez** [comment] 2022-03-11 09:07
@maciej-kolanski-red, could you give a test to this patch that I'm attaching (sorry for the .patch.txt extension, github just doesn't allow uploading .patch files). The patch should detect changes in the network and invalidate existent soup connections, so everything should work properly with the new network. If it works for you, I can commit it to the wpe branch.

[webkit-drop-connection-on-network-change.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8230561/webkit-drop-connection-on-network-change.patch.txt)

**Comment by maciej-kolanski-red** [comment] 2022-03-14 14:01
@magomez The patch works great, thank you very much! I believe this issue can be safely closed once the change is merged.

**Comment by magomez** [comment] 2022-03-14 14:42
Great! I've just pushed 43877edc4454aa4c7e4073aa6658cedfb62756f1 with the patch to the wpe-2.22 branch. Please feel free to close this when you verify that everything is ok. Thanks!

**Comment by maciej-kolanski-red** [comment] 2022-04-01 14:41
@magomez Unfortunately, we have found a regression that is reproducible only for a subset of our platforms. What is happening there is that glib emits the `network-changed` event far too frequently (like every 5-10 seconds), which triggers the libsoup's abort and effectively breaks the application usage. From what I know so far is that the event is caused by some network configuration changes, which in fact do not break the connectivity.

We are still working on the root cause, just wanted to let you know about a possible issue.

**Comment by magomez** [comment] 2022-04-04 10:31
> @magomez Unfortunately, we have found a regression that is reproducible only for a subset of our platforms. What is happening there is that glib emits the `network-changed` event far too frequently (like every 5-10 seconds), which triggers the libsoup's abort and effectively breaks the application usage. From what I know so far is that the event is caused by some network configuration changes, which in fact do not break the connectivity.

mmmm the problem is that we don't get much information about what's really happening with the network interfaces, other than whether something has changed. There's a boolean parameter coming with the network-changed event that should indicate whether there's a network connection active, that the current fix is currently not using. I could use it and drop the connections only if the network is not available, and don't to anything otherwise, but this would only fix the original issue if there's a point where no network is available. If, for example, we have interface 1, then bring up interface 2 and then bring down interface 1, the fix wouldn't work as there's no situation where no network is available.

What do you think @maciej-kolanski-red ? would this be enough?

**Comment by magomez** [comment] 2022-04-04 10:55
I'm thinking that I could also add some API method to allow Thunder to request the open connections to be closed. So, instead of relying on glib notifications, Thunder can request to drop the connections when the device decides that a new network interface has to be used.

**Comment by maciej-kolanski-red** [comment] 2022-04-04 11:01
That's right - we could change it to abort libsoup's connections only on `networkAvailable=false`. I tested it and it indeed solves the regression, but as you've noted, it does not work if there is a switch from one active network interface to some other one (e.g. from wifi to eth). In that case it is insufficient for us.

Ideally we should drop the connections only if the actual active network interface change occurs. I am not sure how hard is it to detect it using glib. The new Thunder API seems to be a good idea.

**Comment by magomez** [comment] 2022-04-05 09:10
> Ideally we should drop the connections only if the actual active network interface change occurs. I am not sure how hard is it to detect it using glib. The new Thunder API seems to be a good idea.

It's not doable through GLib AFAIK. It's not as easy of detecting a change in the active network interface, I'm afraid. There are routing tables affecting here, and also ipv4 vs ipv6. In a simple case, assuming that we're using ipv4 or ipv6 only, and that there aren't specific route rules other than the default, I could get the default interface from /proc/net/route. So when we get the network-changed signal, we can check whether the default gateway has changed, and drop the soup session if it has. Not sure whether this is valid option for you.

**Comment by magomez** [comment] 2022-04-05 09:42
Ok, I think I can handle both ipv4 and ipv6 at the same time. I think I can get the default interface for both (from /proc/net/route and /proc/net/ipv6_route). The idea would be to keep the names of both interfaces around. In response to the network-event signal, we get the interface names again and check whether they have changed. If any of them has changed, drop the soup_session. I think this would cover all the cases.

I'm going to start working on this. It it works, I'll revert the previous patch. Also, I'm going to put this feature behind a build flag, so other users can keep it disabled if they don't need it.

**Comment by magomez** [comment] 2022-04-05 09:52
I've just reverted the original fix for this and I'm going to work on a new approach. Also, this behavior will be kept behind a build flag that's disabled by default, so it doesn't affect other users.

**Comment by maciej-kolanski-red** [comment] 2022-04-06 09:20
Sounds good to me. I believe this way we could reduce number of libsoup's aborts to the minimum and make it work correctly. Please let me know if you need any help with implementation or fix verification.

**Comment by magomez** [comment] 2022-04-06 09:25
> Sounds good to me. I believe this way we could reduce number of libsoup's aborts to the minimum and make it work correctly. Please let me know if you need any help with implementation or fix verification.

Sure, I'll post the patch here as soon as I have it, so you can verify before committing it.

**Comment by magomez** [comment] 2022-04-07 09:02
@maciej-kolanski-red I'm attaching a patch for you to test with the new approach.

How it works:
- You need to build with -DENABLE_NETWORK_CHANGE_DETECTION=ON for it to work (or change the default option value inside OptionsWPE.cmake).
- SoupNetworkSession will connect to the GNetworkMonitor network-changed signal, as before. Instead of calling soup_session_abort directly, it will schedule a call to check whether the interfaces have changed. As there might be many network-changed signals coming in a short amount of time, we will wait until 2 seconds have passed without signals to perform the check. The idea here is to perform the check only once after the network has stabilized.
- The check will read the routing information for both IPV4 and IPV6 from /proc/net/route and /proc/net/ipv6_route respectively, and look for the first interface there that's up and is a gateway, which should be the default interface we're using for that protocol. Bear in mind that this won't work if the system is using custom predefined routes.
- If there was a valid interface being used and it has changed, the call to soup_session_abort is performed. With this we should be able to drop the session only when a valid interface is dropped or replaced.

I've tested this in my system with IPV4 and it works as expected. I haven't been able to test it with IPV6 but I expect it will work in the same way. Please give it a test and tell me whether it fixes the problem for you. I've left some logging to the console to show what's happening and whether there are errors during the process.

[webkit-drop-connection-on-network-change.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8441320/webkit-drop-connection-on-network-change.patch.txt)

**Comment by maciej-kolanski-red** [comment] 2022-04-11 06:34
@magomez The patch looks good to me. We are going to run some extensive tests to make sure it does not introduce any regression. I will come back with a feedback sometime this week.

**Comment by magomez** [comment] 2022-04-29 07:53
@maciej-kolanski-red any news about this? Does the patch fix your problem?

**Comment by maciej-kolanski-red** [comment] 2022-04-29 08:57
@magomez We are still working on verification on IPv6 setup. I will let you know once it's finished. Sorry for the delay, but this change affects all network requests and we just want to avoid any regressions.

**Comment by przemyslaw-gorszkowski-red** [comment] 2022-05-04 11:03
@magomez :  our internal verification tests passed without any regression also with IPv6 setup, so you can merge this change. I have 2 suggestions:
1. can you replace printf with LOG(Network?
2. is it really needed to have this ENABLE_NETWORK_CHANGE_DETECTION env?

**Comment by magomez** [comment] 2022-05-04 11:30
> @magomez : our internal verification tests passed without any regression also with IPv6 setup, so you can merge this change. I have 2 suggestions:
> 
> 1. can you replace printf with LOG(Network?

Sure, no problem.

> 2. is it really needed to have this ENABLE_NETWORK_CHANGE_DETECTION env?

Yes, it's necessary because not all users may want this feature enabled, or it may cause regressions to their existent setups. Having the build option (not sure why you call it env) is the best way to keep this feature only to those that want it.

**Comment by przemyslaw-gorszkowski-red** [comment] 2022-05-04 11:58
> Yes, it's necessary because not all users may want this feature enabled, or it may cause regressions to their existent setups. Having the build option (not sure why you call it env) is the best way to keep this feature only to those that want it.

Ah, yes, sorry, I meant build option not env.
Understood

**Comment by magomez** [comment] 2022-05-04 13:29
@przemyslaw-gorszkowski-red I've just pushed c3333ad7cc48a19f7bc7260ac18eed3566db0d5c to the wpe-2.22 branch with the fix, using LOG instead of printf as you requested. Please verify and close this if everything is ok.

**Comment by przemyslaw-gorszkowski-red** [comment] 2022-05-05 12:52
@magomez : thanks, it works as expected, @maciej-kolanski-red  you can close the ticket

**Closed as completed** 2022-05-05 13:08 UTC
