### ISSUE TITLE
[wpe-2.38] Appearance of darker shades in SVG lightning filter

### ISSUE THREAD

**Issue by amol-virnodkar-infosys** [Metrological/WebKitForWayland#1274] opened 2024-01-11 15:09 UTC
Appearance of darker shades in SVG lightning filter with WPE 2.38, when ACT-1345 test case is executed from BBC cert suite. To reproduce the issue, use WPE 2.38 and run ACT-1345 test case:

https://certification.bbctvapps.co.uk/act/client/ in the WPE-WebKit-based browser
https://certification.bbctvapps.co.uk/act/portal/ locally and pair the two

**WPE 2.38**

![WPE 2 38 ACT-1345](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/148946627/d056c300-cf58-4fb5-a0ca-a23f2f101cb4)

**Comment by pgorszkowski-igalia** [comment] 2024-01-12 14:29
It seems that in case of 2.38 the reason of the darker results is change: https://bugs.webkit.org/show_bug.cgi?id=234118.

This change turns off possibility to use linearRGB colorspace in case of WPE and cairo. I will continue my investigation would it be possible to turn it on without any regression in 2.38 (the test case passes with expected results if I turn it on but I need to consult this with SVG expert)

**Comment by pgorszkowski-igalia** [comment] 2024-02-08 15:31
I created a bug report about this case in upstream: https://bugs.webkit.org/show_bug.cgi?id=268537 and created PR which fixes it: https://github.com/WebKit/WebKit/pull/23663. The fix is waiting for review. After merging it in upstream, I will bakcport it to 2.38 and 2.42

**Comment by pgorszkowski-igalia** [comment] 2024-02-21 15:15
https://github.com/WebKit/WebKit/pull/23663 is merged, but unfortunately there are a lot of difference between upstream and wpe-2.38, so I will have to reimplement few things. I will try to provide a PR for wpe-2.38 as soon as possible

**Comment by pgorszkowski-igalia** [comment] 2024-02-22 10:18
Fix from upstream is backported to wpe-2.38: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1287

@amol-virnodkar-infosys: please check and verify.

**Comment by amol-virnodkar-infosys** [comment] 2024-02-28 18:15
We retested this issue using the fix in the PR: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1287 and could not reproduce the issue. 

Please find below test result of the ACT-1345 using the fix.
<img width="567" alt="svg_withfix" src="https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/148946627/d8aa0e06-9287-444c-812c-f55a101cf1d0">

**Comment by pgorszkowski-igalia** [comment] 2024-02-28 18:37
ok, so I close this ticket.

**Closed as completed by pgorszkowski-igalia** 2024-02-28 18:37 UTC
Labels: wpe-2.38, wpe-2.42
