### ISSUE TITLE
[wpe-2.28] Crash on `libWPEWebInspectorResources.so` missing

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#865] opened 2022-05-26 13:51 UTC
As in title, once the `libWPEWebInspectorResources.so` missing, we get:
```
Core was generated by `WPEProcess -l libWPEFrameworkWebKitBrowserImpl.so -c WebKitImplementation -C Ht'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  WTF::SHA1::addBytes () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+99cd0000fb-r0/git/Source/WTF/wtf/SHA1.cpp:108
108	/usr/src/debug/wpe-webkit/2.28+gitAUTOINC+99cd0000fb-r0/git/Source/WTF/wtf/SHA1.cpp: No such file or directory.
[Current thread is 1 (Thread 0xaf2873e0 (LWP 12))]
#0  WTF::SHA1::addBytes () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+99cd0000fb-r0/git/Source/WTF/wtf/SHA1.cpp:108
#1  0xb2e7ec54 in Inspector::backendCommandsHash () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+99cd0000fb-r0/git/Source/JavaScriptCore/inspector/remote/glib/RemoteInspectorUtils.cpp:67
#2  0xb1d8328a in WebKit::RemoteInspectorClient::setupConnection () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+99cd0000fb-r0/git/Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorClient.cpp:192
#3  0xb1d8d658 in operator() () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+99cd0000fb-r0/git/Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorClient.cpp:176
#4  _FUN () at /usr/src/debug/wpe-webkit/2.28+gitAUTOINC+99cd0000fb-r0/git/Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorClient.cpp:181
#5  0xb0b5109a in g_task_return_now (task=0xade0b078) at ../glib-2.62.4/gio/gtask.c:1212
#6  0xb0b518e6 in g_task_return (type=<optimized out>, task=0xade0b078) at ../glib-2.62.4/gio/gtask.c:1281
#7  g_task_return (task=0xade0b078, type=<optimized out>) at ../glib-2.62.4/gio/gtask.c:1238
#8  0xb0b4b15c in g_socket_client_async_connect_complete (data=0xade06b18) at ../glib-2.62.4/glib/gmem.h:209
#9  0xb0b4b53e in g_socket_client_connected_callback (source=<optimized out>, result=<optimized out>, user_data=0xade238d0) at ../glib-2.62.4/gio/gsocketclient.c:1656
#10 0xb0b5109a in g_task_return_now (task=0xade0b480) at ../glib-2.62.4/gio/gtask.c:1212
#11 0xb0b518e6 in g_task_return (type=<optimized out>, task=0xade0b480) at ../glib-2.62.4/gio/gtask.c:1281
#12 g_task_return (task=0xade0b480, type=<optimized out>) at ../glib-2.62.4/gio/gtask.c:1238
#13 0xb0b4c4ce in g_socket_connection_connect_callback (socket=<optimized out>, condition=<optimized out>, user_data=0xade0b480) at ../glib-2.62.4/gio/gsocketconnection.c:237
#14 0xb0b47956 in socket_source_dispatch (source=0xade239b8, callback=0xb0b4c4ad <g_socket_connection_connect_callback>, user_data=0xade0b480) at ../glib-2.62.4/gio/gsocket.c:3961
#15 0xb1885864 in g_main_dispatch (context=0xade005f8) at ../glib-2.62.4/glib/gmain.c:3216
#16 g_main_context_dispatch (context=context@entry=0xade005f8) at ../glib-2.62.4/glib/gmain.c:3885
#17 0xb18859ce in g_main_context_iterate (context=0xade005f8, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib-2.62.4/glib/gmain.c:3958
#18 0xb1885d08 in g_main_loop_run (loop=0xade031a0) at ../glib-2.62.4/glib/gmain.c:4152
#19 0xb3936058 in WPEFramework::Plugin::WebKitImplementation::Worker (this=0x22a108) at /usr/src/debug/webkitbrowser-plugin/3.0+gitAUTOINC+5c498fd05a-r1/git/WebKitBrowser/WebKitImplementation.cpp:2531
#20 0xb3e88532 in WPEFramework::Core::Thread::StartThread (cClassPointer=0x22a108) at /usr/src/debug/wpeframework/1.99+gitAUTOINC+54c2404197-r0/git/Source/core/Thread.cpp:172
#21 0xb3c2b79e in start_thread (arg=0xe0572675) at pthread_create.c:477
#22 0xb3ce322c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from rootfs/lib/libc.so.6
```

**Comment by magomez** [comment] 2022-05-27 08:21
@Scony how are you reproducing this? libWPEWebInspectorResources.so should be installed when wpe gets installed. Can you provide more information about how this is happening?

**Comment by Scony** [comment] 2022-05-30 11:03
@magomez Apparently I'm using broken configuration. Nevertheless, the crash should not happen in any case I guess.

**Comment by magomez** [comment] 2022-05-31 09:10
> @magomez Apparently I'm using broken configuration. Nevertheless, the crash should not happen in any case I guess.

That library is a dependency that needs to be installed, like many others as libsoup, GStreamer, EGL, etc. We don't check whether those are available on runtime. We know that they were there in order to build (which is when they were checked) and it's assumed that they will be there when running WPE. In this case, if the library is generated by the WPE build and installed into the appropriate directory, then we don't have bug. If after that, during the generation of the image the library is not placed where it should, then the bug is in the image generation, but not in WPE, which did as expected.

**Comment by emutavchi** [comment] 2022-05-31 12:13
@magomez we have deployments where libWPEWebInspectorResources.so is not installed in rootfs. Instead, it is downloaded at runtime immediately after boot, but after the browser has to be launched (i.e. browser is started before device is online). It works fine with wpe-2.22, but it is crashing with wpe-2.28. probably because of HTTP RWI.

**Comment by magomez** [comment] 2022-06-21 13:43
Yes, it seems that the problem comes from the HTTP RWI. Before that, the library would be needed only when some client connected to the inspector, but now it's required when the browser is launched, as that's where the inspector server is started and needs to be configured.
I've worked on some changes in order to gracefully handle the scenario that you mention, where libWPEWebInspectorResources.so won't be available when the browser is launched, but it's supposed to be once the network connection is enabled. The idea here is that when the browser is launched, the inspector will try to load the library every 10 seconds, until the library is loaded or 60 seconds have passed. If the library is made available before those 60 seconds, the inspector will work properly. If after those 60 seconds the library wasn't loaded then the inspector won't work. I'm attaching a patch with these changes so you can test it. Please tell me whether it fixes for you as well and I'll commit it.

[2.28-delay-inspector-setup.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8949427/2.28-delay-inspector-setup.patch.txt)

**Comment by Scony** [comment] 2022-06-21 14:05
Thanks @magomez I'll check it out

**Comment by Scony** [comment] 2022-06-22 15:35
@magomez it works well on my end, you can ship it.

**Comment by magomez** [comment] 2022-06-22 16:39
I've just pushed 2ca0a82359841e9f63b3efdb856aebee58edbfc4 to the wpe-2.28 branch with the fix. Please verify and close this if everything works fine.

**Comment by woutermeek** [comment] 2022-06-30 12:08
@Scony closing this issue, please re-open if an issue occurs with the fix.

**Closed as completed by woutermeek** 2022-06-30 12:08 UTC
