### ISSUE TITLE
WPEWebProcess is crashing when access Wikipedia OTT app

### ISSUE THREAD

**Issue by zbigniew-holdys-epam** [Metrological/WebKitForWayland#749] opened 2021-11-25 09:38 UTC
Crash Scenario:
This crash happens while launching Wikipedia app

Affected Version:
WPE2.22

Reproduction:
https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.Wikipedia==[x]route:home

Unfortunately this app doesnt work on PC browser (chrome/chromium) but on STB only.
The main reason behind this is a missing Language value that STB can fetch using websocket connection on 10016 and 10415 ports.
But this can be easily workarounded using webinspector by setting the value manually (i.e "en", "nl", "pl")

it crashes 100% times on STB, and RaspberryPI on WPE2.22 version.

I couldnt reproduce it on WebkitGTK2.30 / epiphany (Webkit 2.34.1) / Chromium / Chrome / Firefox

It looks the problem is known in Webkit developers community 
https://bugs.webkit.org/show_bug.cgi?id=194196 

It is caused by mysterious timer related crashes that are only explainable by UAF, thread safety, etc...

0)  0xb5fb1826 in WTFCrash () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WTF/wtf/Assertions.cpp:272
1)  0xb5529a9a in WebCore::TimerBase::setNextFireTime () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/Timer.cpp:381
2)  0xb5529bbc in WebCore::TimerBase::start () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/Timer.cpp:223
3)  0xb556c67e in WebCore::TimerBase::startOneShot () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/Timer.h:57
4)  WebCore::FontCache::fontForFamily () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/graphics/FontCache.cpp:326
5)  0xb514af92 in WebCore::CSSFontSelector::fontRangesForFamily () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/css/CSSFontSelector.cpp:314
6)  0xb556c7ac in operator() () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/graphics/FontCascadeFonts.cpp:147
7)  __visit, WebCore::realizeNextFallback(const WebCore::FontCascadeDescription&, unsigned int&, WebCore::FontSelector*):: >, const WTF::Variant > () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/build/DerivedSources/ForwardingHeaders/wtf/Variant.h:1901
8)  __visit, WebCore::realizeNextFallback(const WebCore::FontCascadeDescription&, unsigned int&, WebCore::FontSelector*):: >, const WTF::Variant&> () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/build/DerivedSources/ForwardingHeaders/wtf/Variant.h:1938
9)  __visit, WebCore::realizeNextFallback(const WebCore::FontCascadeDescription&, unsigned int&, WebCore::FontSelector*):: >, const WTF::Variant&> () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/build/DerivedSources/ForwardingHeaders/wtf/Variant.h:1938
10) __visit, WebCore::realizeNextFallback(const WebCore::FontCascadeDescription&, unsigned int&, WebCore::FontSelector*):: >, const WTF::Variant&> () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/build/DerivedSources/ForwardingHeaders/wtf/Variant.h:1980
11) visit, WebCore::realizeNextFallback(const WebCore::FontCascadeDescription&, unsigned int&, WebCore::FontSelector*):: >&, const WTF::Variant&> () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/build/DerivedSources/ForwardingHeaders/wtf/Variant.h:1988
12) realizeNextFallback () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/graphics/FontCascadeFonts.cpp:158
13) 0xb556c91a in WebCore::FontCascadeFonts::realizeFallbackRangesAt () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/graphics/FontCascadeFonts.cpp:184
14) 0xb518f31e in WebCore::FontCascadeFonts::primaryFont () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/graphics/FontCascadeFonts.h:128
15) 0xb519f6a2 in WebCore::FontCascade::primaryFont () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/platform/graphics/FontCascade.h:330
16) WebCore::StyleResolver::StyleResolver () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/css/StyleResolver.cpp:225
17) 0xb57a7006 in std::make_unique () at /usr/include/c++/6.4.0/bits/unique_ptr.h:791
18) WebCore::Style::Scope::resolver () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/style/StyleScope.cpp:100
19) 0xb57a7e36 in WebCore::Style::TreeResolver::Scope::Scope () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/style/StyleTreeResolver.cpp:67
20) 0xb57ae188 in WebCore::Style::TreeResolver::resolve () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/style/StyleTreeResolver.cpp:549
21) 0xb51f2eec in WebCore::Document::resolveStyle () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/dom/Document.cpp:1857
22) 0xb51f3388 in WebCore::Document::updateStyleIfNeeded () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/dom/Document.cpp:1975
23) 0xb51f4c38 in WebCore::Document::finishedParsing () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/dom/Document.cpp:5461
24) 0xb539e798 in WebCore::HTMLDocumentParser::prepareToStopParsing () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/html/parser/HTMLDocumentParser.cpp:141
25) 0xb539e804 in WebCore::HTMLDocumentParser::finish () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/html/parser/HTMLDocumentParser.cpp:476
26) 0xb541d056 in WebCore::DocumentWriter::end () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/loader/DocumentWriter.cpp:284
27) 0xb54272ee in WebCore::DocumentLoader::finishedLoading () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/loader/DocumentLoader.cpp:433
28) 0xb5428240 in WebCore::DocumentLoader::maybeLoadEmpty () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/loader/DocumentLoader.cpp:1677
29) 0xb5429560 in WebCore::DocumentLoader::startLoadingMainResource () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/loader/DocumentLoader.cpp:1693
30) 0xb5431036 in WebCore::FrameLoader::init () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/loader/FrameLoader.cpp:313
31) 0xb5873e7e in WebCore::SVGImage::dataChanged () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/svg/graphics/SVGImage.cpp:480
32) 0xb5369fb0 in WebCore::ImageBitmap::createFromBuffer () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/html/ImageBitmap.cpp:618
33) 0xb536f0f8 in WebCore::PendingImageBitmap::createImageBitmap () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/html/ImageBitmap.cpp:586
34) WebCore::PendingImageBitmap::didFinishLoading () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/html/ImageBitmap.cpp:569
35) 0xb52c5792 in WebCore::FileReaderLoader::didFinishLoading () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/fileapi/FileReaderLoader.cpp:227
36) 0xb54587b4 in WebCore::ThreadableLoaderClientWrapper::didFinishLoading () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/loader/ThreadableLoaderClientWrapper.h:79
37) operator() () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/loader/WorkerThreadableLoader.cpp:225
38) call () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/build/DerivedSources/ForwardingHeaders/wtf/Function.h:101
39) 0xb587bc06 in WebCore::WorkerRunLoop::runInMode () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/workers/WorkerRunLoop.cpp:201
40) 0xb587bcdc in WebCore::WorkerRunLoop::run () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/workers/WorkerRunLoop.cpp:137
41) 0xb587c278 in WebCore::WorkerThread::workerThread () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WebCore/workers/WorkerThread.cpp:205
42) 0xb5fc5044 in WTF::Function::operator()() const () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WTF/wtf/Function.h:56
43) WTF::Thread::entryPoint () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WTF/wtf/Threading.cpp:136
44) 0xb5fde47c in wtfThreadEntryPoint () at /usr/src/debug/wpe-webkit/1_2.22.1+git-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215
45) 0xb48ca616 in start_thread (arg=0x0) at /usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458
46) 0xb445ef12 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:86 from ./work/68c1b847866937dd5e6915d71630bdc2/lib/libc.so.6

**Comment by modeveci** [comment] 2021-12-17 09:35
_From RDK Jira ticket:_

One of the easiest way to reproduce this issue is to use webinspector and set the breakpoint in  appBoundle.es5.js  in function X()
arround 579 line (formatted version of the obfuscated file)
}, X = function language(n) {
   return Y("language", n) // here set n="en"
},$ = window.lng;
 
and set n="en"

**Comment by magomez** [comment] 2021-12-22 16:31
This is a tricky one...

I've been able to reproduce a crash by following these steps:
- load the URL
- put a breakpoint in the place mentioned and set n="en" a couple of times, which allows the page to load
- add some text to the search field. Eventually it will crash when loading content related to the entered text.

The backtrace I got from the crash is quite similar to the one provided, except that the assertion crashing is not the same, just the one before that in the code: https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/3aac0dbc6518f344ca6245a0a5c76cadc2f776ab/Source/WebCore/platform/Timer.cpp#L380

The problem here is that there are several workers threads loading content at the same time, and they are also loading fonts for that content. The used fonts are stored in FontCache, which is a singleton which is not thread-safe, which leads to a situation where a thread that's not the main one tries to schedule a timer that belongs to the main thread, and hence the assertion.

I've been able to replace the problematic timer with one that runs on the main thread no matter which thread schedules it, and also add some locks to FontCache so it can be used from several threads. This removes the reported crash.

But... once this crash is fixed, a new one comes up. With the same steps than before, the new crash will happen when the page finishes loading. This one comes from the assertion in FrameLoader::checkCompleted(), but I'm still trying to find out why it's happening.

I'll keep you updated with what I can find.

**Comment by magomez** [comment] 2022-01-07 12:01
I've been doing more investigation on this, and the problem seems to be the extensive usage of createImageBitmap and OffscreenCanvas that the application does. Let me elaborate.

On 2.22 we have createImageBitmap and OffscreenCanvas enabled, despite the features are not complete (they are fully implemented on 2.34). There are some pieces to fix regarding concurrency when drawing to a canvas on a secondary thread. Both features are enabled because they improve a bit lightning's applications performance, and the usage that most apps do is pretty simple (what's currently implemented is enough). But the Wikipedia app that causes the crash seems to use these features extensively, and that leads to problems. The original crash happens precisely because the app has several threads rendering text to offscreen canvases. And the crash I found after fixing the first one is also related to concurrency issues. Just disabling createImageBitmap and OffscreenCanvas makes the crashes go away.

I'm afraid there's no way to fix these concurrency issues without fully implementing OffscreenCanvas support, and that's not an option because the changes required to do that are huge (the code has diverged a lot between 2.22 and 2.34). So I'm afraid the only solution I see to this is disabling the problematic features. This has a small performance penalty, but I'm run some tests and the loss is not very big.

**Comment by magomez** [comment] 2022-01-07 12:54
I forgot to specify that the threading problem happens because the offscreen canvas is being used inside a service worker. Using it in the main thread is not a problem, but the current code is not thread safe to use it on a service worker.

**Comment by jacek-skiba-red** [comment] 2022-01-10 08:07
@magomez: thanks for detail analyze. Few questions:

- Service worker API is disabled in our case. You are referring to web worker api (which is used in all lightning applications)?
- Through web inspector I don't see usage of OffscreenCanvas API in Wikipedia app (I see calls to createImageBitmap)
- Can you provide for reference PR for this change - we like to test in on our platforms

**Comment by magomez** [comment] 2022-01-10 09:12
> * Service worker API is disabled in our case. You are referring to web worker api (which is used in all lightning applications)?

It's web workers then. I haven't checked the app code, I just know that there are several threads running there, so I assumed they were service workers. But they can be web workers as well, as you say.

> * Through web inspector I don't see usage of OffscreenCanvas API in Wikipedia app (I see calls to createImageBitmap)

That's weird. I'm seeing secondary threads accessing font data, and I assumed it was for OffscreenCanvas. Not sure how they are used then. But the problem is related to OffscreenCanvas and createImageBitmap for sure.

> * Can you provide for reference PR for this change - we like to test in on our platforms

```
Sure. The patch is pretty simple:
diff --git a/Source/WebKit/Shared/WebPreferences.yaml b/Source/WebKit/Shared/WebPreferences.yaml
index 72e95db57201..657d9a561b60 100644
--- a/Source/WebKit/Shared/WebPreferences.yaml
+++ b/Source/WebKit/Shared/WebPreferences.yaml
@@ -1177,7 +1177,7 @@ SpringTimingFunctionEnabled:
 
 ImageBitmapOffscreenCanvasEnabled:
   type: bool
-  defaultValue: true
+  defaultValue: false
   humanReadableName: "ImageBitmap and OffscreenCanvas"
   humanReadableDescription: "Support for the ImageBitmap and OffscreenCanvas APIs"
```

**Comment by magomez** [comment] 2022-01-10 09:15
I was going to push this change so you can test it, but it would be great if you could test this before, and I'll push it if you verify that the problem is gone on your side as well.

**Comment by magomez** [comment] 2022-01-10 09:34
Ah, I was so focused on the OffscreenCanvas theory that I missed a key point in the backtrace. It's not Offscreen canvas, but createImageBitmap the one that's being run on a worker thread. And it's loading an SVG image the one that's accessing font information from a worker thread. In any case, the patch works because it disables createImageBitmap as well.

**Comment by zbigniew-holdys-epam** [comment] 2022-01-10 17:18
It looks disabling ImageBitmapOffscreenCanvasEnabled has successful solved this ticket. 
We have roughly made a few GFX benchmarks to check if the performance decreases.
So far we haven't observed any significant regressions or delays. I assume we can close this ticket

**Comment by magomez** [comment] 2022-01-11 08:08
I continued investigating this, as I wanted to avoid disabling createImageBitmap, and I finally found a solution that will remove the crash when loading SVG images. I've just pushed 1c7ef305905f60d9d87832adb00b9e54b37e0c40 to the wpe-2.22 branch with the fix. Could you remove the patch to disable createImageBitmap and test that this commit fixes the issue for you, please?

**Comment by zbigniew-holdys-epam** [comment] 2022-01-11 18:47
I have reverted "disabling createImageBitmap" patch and applied your current "Fix crash decoding SVG images on worker threads". After round of testing everything looks correct. I haven't observed any regressions.

BTW. What I am using for GFX benchmarking :
https://webglsamples.org/aquarium/aquarium.html
https://orange-opensource.github.io/orangemark/
https://browserbench.org/MotionMark1.2/

do you recommend any better?
Cheers

**Comment by magomez** [comment] 2022-01-12 08:30
> I have reverted "disabling createImageBitmap" patch and applied your current "Fix crash decoding SVG images on worker threads". After round of testing everything looks correct. I haven't observed any regressions.

Great, let's keep this fix then!! Could you close this if the fix is verified, please?

> BTW. What I am using for GFX benchmarking : https://webglsamples.org/aquarium/aquarium.html https://orange-opensource.github.io/orangemark/ https://browserbench.org/MotionMark1.2/
> 
> do you recommend any better? Cheers

All or those are fine, and I use them too. But specifically for lightning apps I use https://strike.lightningjs.io/es6/

**Comment by woutermeek** [comment] 2022-05-20 11:37
@zbigniew-holdys-epam closing this, if there is an issue with this please re-open.

**Closed as completed by woutermeek** 2022-05-20 11:37 UTC
