### ISSUE TITLE
Canvas related patch causing  memory leak in Amlogic platform

### ISSUE THREAD

**Issue by nrajan002c** [Metrological/WebKitForWayland#834] opened 2022-04-21 02:29 UTC
After this patch https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/d852c5036ef93b9e469203adbdca5eb63bc6a4b8  added in 2.22 branch, It is causing memory leak in specific gaming apps like "https://comcast.play.works/prod/reg/apps/puppy_rescue/index.html?parent=portal_4&platform=xglobal&us_privacy=1-N-&lmt=0" 
Memory is spiking to maximum and the browser instance killed by monitoring plugin (rdkservices).

This issue is happening only amlogic devices. It is not observed with other arm devices in comcast.

note: In 2.28 build, this issue is not observed in amlogic too.

**Comment by magomez** [comment] 2022-04-26 08:37
I've been testing this and I'm not able to reproduce the leak in any of the platforms that have available. It's quite weird that the leak is only happening on a single platform but, who knows. As I cannot reproduce the issue, I'll need you @nrajan002c to perform some tests for me, to try to get some information about what's happening here.

First, and just to be sure that there's a memory leak, what's the amount of memory available to the browser in that platform before it gets killed? I see that the example app you sent takes around 230-240MB or memory. Is that available on the platform? Or maybe it's too much and the browser is killed?

According to your report, this started happening after https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/d852c5036ef93b9e469203adbdca5eb63bc6a4b8 was added. Are you sure there was no problem before that commit?. That change affects the accelerated canvas, yes, and fixes a situation where no content might be shown, but it should not create a leak. Could you double check whether this commit is really the culprit of the leak?

And finally, I've created a patch that logs how the canvas related buffers are being created and destroyed after that commit. Please, apply it, give the test a run, and send the output back to me so I can try to find what's happening there.

[debug-platform-layer-buffers.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8561314/debug-platform-layer-buffers.patch.txt)

**Comment by woutermeek** [comment] 2022-05-04 13:58
@nrajan002c could you please check the patch?

**Comment by nrajan002c** [comment] 2022-05-05 20:11
Hi @magomez  @woutermeek 
I have attached the log with debug enabled . [log-.txt]  
 (https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8635781/log-.txt)
 
 Here the url is "https://comcast.play.works/prod/reg/apps/math_time/index.html?parent=portal_4&platform=xglobal&us_privacy=1-N-&lmt=0"

Webprocess got killed at this point,
`2022 May 05 19:36:49.781308 /usr/bin/WPEFramework[23878]:  [Thu, 05 May 2022 19:36:49 ]:[Monitor.h:965]: Fatal: FORCED Shutdown: HtmlApp-0 by reason: MemoryExceeded.`

We have enough memory in this device (3GB RAM). When app is launching, memory is spiking and got killed by the Monitor plugin which has the  threshold limit (650M) for html application.

**Comment by magomez** [comment] 2022-05-10 12:52
I'm afraid the log didn't provide much info, as the buffers that I suspected might be creating the leak seem to be properly created and destroyed.

Before trying any other thing, @nrajan002c , in which commit are you in the wpe-2.22 branch? Do you have 3aac0dbc6518f344ca6245a0a5c76cadc2f776ab , which is a fix for a potential leak that was happening after the commit you mention as the culprit of the leak? If you don't have 3aac0dbc6518f344ca6245a0a5c76cadc2f776ab, could you cherry-pick it and test whether it fixes the problem?

If you already have that commit, let's try another thing: as you mention that this is not reproducible with the 2.28 code, I've performed some changes to the implementation so it's more similar to the 2.28 one, hoping that will fix the problem. I'm attaching a patch with the changes here. Could you test it and check whether the problem gets fixed?

[fix-canvas-leak.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8661650/fix-canvas-leak.patch.txt)

**Comment by magomez** [comment] 2022-05-10 12:53
I'm afraid the log didn't provide much info, as the buffers that I suspected might be creating the leak seem to be properly created and destroyed.

Before trying any other thing, @nrajan002c , in which commit are you in the wpe-2.22 branch? Do you have 3aac0dbc6518f344ca6245a0a5c76cadc2f776ab , which is a fix for a potential leak that was happening after the commit you mention as the culprit of the leak? If you don't have 3aac0dbc6518f344ca6245a0a5c76cadc2f776ab, could you cherry-pick it and test whether it fixes the problem?

If you already have that commit, let's try another thing: as you mention that this is not reproducible with the 2.28 code, I've performed some changes to the implementation so it's more similar to the 2.28 one, hoping that will fix the problem. I'm attaching a patch with the changes here. Could you test it and check whether the problem gets fixed?

[fix-canvas-leak.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8661650/fix-canvas-leak.patch.txt)

**Comment by nrajan002c** [comment] 2022-05-11 12:37
Hi @magomez 
This patch 'fix-canvas-leak.patch.txt' patch is resolving the memory leak issue with the mentioned app playback in Amlogic device. I will do some more testing and confirm. 
Thanks.

**Comment by nrajan002c** [comment] 2022-05-17 15:07
Hi @magomez 
Could you please merge this patch in 2.22 branch ?

**Comment by magomez** [comment] 2022-05-18 08:59
I've just pushed 5d7f2eeeac252561d8db62a93c07e3f60452ee87 to the wpe-2.22 branch with the patch. Please verify and close this if everything is ok.

**Comment by woutermeek** [comment] 2022-05-20 11:09
@nrajan002c closing this issue, if anything comes up please re-open.

**Closed as completed by woutermeek** 2022-05-20 11:09 UTC
