### ISSUE TITLE
[wpe-2.28] [gstreamer] Quick seeking audio returns to wrong playback position

### ISSUE THREAD

**Issue by laurence-ejraee** [Metrological/WebKitForWayland#1177] opened 2023-09-12 21:09 UTC
Hi, I was hoping someone could look into what I believe may be a bug in either webkit playback position handling or gstreamer position query.
When I carry out very fast seek forward on simple audio element I see seeked events occur for each seek time, however the audio then moves back to and continues playing from only one seek forwards (e.g. +10s instead of a total +50s for 5 seeks).
I can reproduce this issues with the simple test case provided.

I see the follow html console output for the demo:
> [Log] do seek (audioQuickSeek, line 24)
[Log] Time update event:  – 0 (audioQuickSeek, line 16)
[Log] do seek (audioQuickSeek, line 24, x2)
[Log] Time update event:  – 20 (audioQuickSeek, line 16, x2)
[Log] do seek (audioQuickSeek, line 24)
[Log] Time update event:  – 30 (audioQuickSeek, line 16)
[Log] do seek (audioQuickSeek, line 24)
[Log] Time update event:  – 40 (audioQuickSeek, line 16, x2)
[Log] Time update event:  – 10.056 (audioQuickSeek, line 16)
[Log] Time update event:  – 10.32 (audioQuickSeek, line 16)
[Log] Time update event:  – 10.56 (audioQuickSeek, line 16)
[Log] Time update event:  – 10.8 (audioQuickSeek, line 16)

I see these gstreamer logs which suggests that the seeks are all carried out, however when gstreamer is queried for the current position it has not yet updated to the new audio position after the final seek and instead returns an earlier position - log extract attached.

Any help or pointing in the correct direction is much appreciated.

[quick-audio-seeking-fail-html.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12590924/quick-audio-seeking-fail-html.txt)
[playbackPosition incorrect gst extract.log](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12590926/playbackPosition.incorrect.gst.extract.log)

**Comment by eocanha** [comment] 2024-06-05 10:57
I've reproduced the issue. It's specifically related to initial seeks, that is, seeks that have to be done before the media has started playing back for the first time. Those are a special case in GStreamer that might not be fully supported.

If you add a setTimeout() that delays the test case actions 5 seconds (so the playback is at ~3.87 in my specific case), the seeks to 13.87, 23.87, 33.87, 43.87, 53.87 are properly handled.

Now that I have the problem more or less bounded, I'm trying to look for a possible fix to it. I'll keep you updated.

**Comment by eocanha** [comment] 2024-06-06 09:45
Ok, I debugged the problem a bit more until I found [the place that is ignoring the initial seeks](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.28/Source/WebCore/html/HTMLMediaElement.cpp#L2989). The initial seeks are being ignored [because the spec says so](https://html.spec.whatwg.org/multipage/media.html#seeking) (look for "If the [media element](https://html.spec.whatwg.org/multipage/media.html#media-element)'s [readyState](https://html.spec.whatwg.org/multipage/media.html#dom-media-readystate) is [HAVE_NOTHING](https://html.spec.whatwg.org/multipage/media.html#dom-media-have_nothing), return." there).

There isn't much I can do to change that behaviour without breaking other things. I'm closing this issue as invalid by now. If you find an alternate way to expect the behaviour you need in a way that complies with the spec, feel free to reword and reopen the issue.

**Comment by laurence-ejraee** [comment] 2024-06-06 09:48
Thanks for your investigation, issue is fine to be closed I think we fixed this on the app side.

**Closed as not planned** 2024-06-06 09:47 UTC
