### ISSUE TITLE
WPENetworkProcess crashes when dropping open connections on network change

### ISSUE THREAD

**Issue by goruklu** [Metrological/WebKitForWayland#818] opened 2022-03-25 17:56 UTC
this commit https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/43877edc4454 seems to trigger a crash when a new network interface is created:

call stack: 
```[ 00 ] g_io_stream_get_output_stream
[ 01 ] g_task_propagate_error
[ 02 ] g_type_check_instance_cast
[ 03 ] g_task_return_now
[ 04 ] g_task_return
[ 05 ] connect_async_message_finished
[ 06 ] soup_session_process_queue_item
[ 07 ] soup_session_async_cancel_message
[ 08 ] soup_session_cancel_message
[ 09 ] soup_session_real_flush_queue
[ 10 ] soup_session_abort
[ 11 ] g_closure_invoke
[ 12 ] signal_emit_unlocked_R
[ 13 ] g_signal_emit_valist
[ 14 ] g_signal_emit
[ 15 ] emit_network_changed
[ 16 ] g_main_context_dispatch
[ 17 ] g_main_context_iterate
[ 18 ] g_main_loop_run
```
Logs:
```
[:39](https://cim.slack.com/archives/D6H88RW3V/p1648229988130769)
2022 Mar 25 15:56:27.273116 WPEFramework[5376]:  [ResidentApp]:main.bundle.5.3.2-7e447087.js:2,4260350 [15:56:27:0257] DEBUG: PluginStateController: Got plugin state change: {"callsign":"org.rdk.UsbAccess","state":"Deactivation","reason":"Requested"}
2022 Mar 25 15:56:27.273717 SearchAndDiscovery[7487]:  failed to get interface with name 'dobby0' (31 - No such device)
2022 Mar 25 15:56:27.274272 SearchAndDiscovery[7487]:  Interface dobby0 does not exist
2022 Mar 25 15:56:27.285197 SearchAndDiscovery[7487]:  created bridge device name 'dobby0'
2022 Mar 25 15:56:27.314078 SearchAndDiscovery[7487]:  setting link address to '100.64.11.1/24 inet dev 0 scope nowhere'
2022 Mar 25 15:56:27.334983 WPENetworkProce[5617]:  g_object_ref: assertion 'G_IS_OBJECT (object)' failed
2022 Mar 25 15:56:27.351479 SearchAndDiscovery[7487]:  setting link address to '2080:d0bb:1e::6440:b01/64 inet6 dev 0 scope nowhere'
2022 Mar 25 15:56:27.353242 WPENetworkProce[5617]:  g_object_set_data_full: assertion 'G_IS_OBJECT (object)' failed
2022 Mar 25 15:56:27.354829 SearchAndDiscovery[7487]:  failed to get interface with name 'dobby_tap0' (31 - No such device)
2022 Mar 25 15:56:27.355510 SearchAndDiscovery[7487]:  Interface dobby_tap0 does not exist
2022 Mar 25 15:56:27.356104 SearchAndDiscovery[7487]:  'dobby_tap0' MAC address is 42:da:01:99:cd:ad
2022 Mar 25 15:56:27.356607 SearchAndDiscovery[7487]:  setting 'dobby0' MAC address to 42:da:01:99:cd:ad
2022 Mar 25 15:56:27.357070 WPEWebProcess[5622]:  [AAMP-PLAYER][-1][WARN][getActiveInterfaceEventHandler][659]getActiveInterfaceEventHandler EventId 55 activeinterface dobby0

2022 Mar 25 15:56:28.779601 WPEFramework[5376]:  ERROR: WebLoaderStrategy::networkProcessCrashed: failing all pending resource loaders
2022 Mar 25 15:56:28.795870 WPEFramework[5376]:  /usr/src/debug/wpe-webkit/2.22.5+gitAUTOINC+3a5aeccf6a-r0/git/Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp(469) : void WebKit::WebLoaderStrategy::networkProcessCrashed()
2022 Mar 25 15:56:28.796499 WPEFramework[5376]:  [ResidentApp]::0,0 WebSocket network error: Network process crashed.
```

**Comment by magomez** [comment] 2022-03-28 13:34
Arg, this seems to be a problem inside glib or libsoup. That's going to be tricky. @goruklu which version of those libraries are you using? Let's see if I can reproduce this somehow.

**Comment by woutermeek** [comment] 2022-03-28 17:07
@goruklu correct me if I'm wrong but from yocto recipe I'm seeing  glib networking 2.48.2 and liboup 2.4

**Comment by goruklu** [comment] 2022-03-28 17:16
![Screen Shot 2022-03-28 at 10 11 49 AM](https://user-images.githubusercontent.com/143648/160451691-86ae0441-2630-4603-a9fc-2577a71c53fd.png)
from the stack trace it looks like
we have libsoup 2.68.4 and glib 2.62.4

**Comment by emutavchi** [comment] 2022-03-28 17:33
libsoup 2.68.4 is available in the sprint. stable and release branches are on libsoup 2.58.1 version. 

as for glib networking: we use use glib-openssl backend 2.50.3.

**Comment by magomez** [comment] 2022-03-29 08:01
> libsoup 2.68.4 is available in the sprint. stable and release branches are on libsoup 2.58.1 version.

Is this happening in both versions? The version I tested when testing the problematic patch was 2.62.3 and the crash was not reproducible for me. Maybe it's a recent bug in libsoup? I'll test 2.68.4 and try to reproduce on my side.

**Comment by magomez** [comment] 2022-03-31 15:14
I've been giving a look to the libsoup, but I'm not very familiar with the code, and without being able to reproduce the crash I can't understand how we're achieving the problematic situation in order to try to fix it. I think we're trying to access a GTask that has already been destroyed, but can't find how we're getting there. In fact there are several g_return_if_fail (G_IS_TASK (task)) lines during the execution that should have failed if the task had been destroyed beforehand. It could be a race condition somewhere though. Is this reproducible always or is it random?

@goruklu , in the image attached a bit above, the backtrace seems to have a bit more information than the one provided in the first comment. Could you paste the complete backtrace here, please? Maybe I'm lucky and there's some extra clue there.

Apart from that, the commit that caused this is intended to close all open connections when there's a network change, cause libsoup keeps open connections that would become invalid if the network connection is changed (may keep them forever if the timeout is set to 0). I don't know whether this feature is interesting for you or not (you should not need it if you're using SOUP_MESSAGE_NEW_CONNECTION or if you have a small timeout for the connections). If you don't need that feature, I can just simply add a flag to enable/disable it, so you can keep it disabled and this would be fixed. WDYT? (this feature wasn't been used before the commit, and it was requested by another WPE user, so I think you shouldn't need it).

**Comment by goruklu** [comment] 2022-03-31 16:52
@magomez I've attached the callstack info:
[6c2bc3f0.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8391553/6c2bc3f0.txt)

May I ask why all open connections are closed when any network change is detected ? In our use case, a new network interface is getting added which causes the crash. The existing connections should not be effected with this change.

we currently patched WPE and reverted the changes. Until a proper fix is found a build option would be a good solution so that we can get rid of our revert patch.

**Comment by magomez** [comment] 2022-04-01 07:52
> @magomez I've attached the callstack info: [6c2bc3f0.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8391553/6c2bc3f0.txt)

Thanks!

> May I ask why all open connections are closed when any network change is detected ? In our use case, a new network interface is getting added which causes the crash. The existing connections should not be effected with this change.

The problem is that we don't get detailed information about the state of the network interfaces, but just a signal indicating that something has changed (not even if something was added or removed). In this case (just adding a new interface) it doesn't affect the existent connections. But it can happen that after this, the old interface that was being used is disabled and the app needs to use the new one, and this requires to close the open connections as they won't work anymore.

> we currently patched WPE and reverted the changes. Until a proper fix is found a build option would be a good solution so that we can get rid of our revert patch.

Ok, I'll add a build option to disable this behavior.

**Comment by magomez** [comment] 2022-04-01 08:34
I have just added ef825bae028a1802192619196551822d9b06b665 to the wpe-2.22 branch. This adds a build option to enable/disable network change detection. The option is enabled by default, so in order to avoid the crash you should build with -DENABLE_NETWORK_CHANGE_DETECTION=OFF.

In any case, it would be awesome if you could if the problem is reproducible with libsoup 2.62.3, cause it seems to be working there. I think the problem might be related to a libsoup deprecated API that wpe-2.22 is using. This API is marked as deprecated, but still usable, and maybe there's some bug when using that API in newer libsoup versions. The wpe-2.28 branch uses the new API already.

**Comment by magomez** [comment] 2022-04-05 09:50
I've just reverted the patch that was causing this problem. I'll try to fix the network interface change problem in some other way, but I'll keep the new behavior behind a build flag, so I won't bother you anymore. So you can just pull the latest changes and this problem won't happen anymore.

**Comment by magomez** [comment] 2022-04-05 12:19
I'm closing this as reverting the problematic patch removed this crash.

**Closed as completed by magomez** 2022-04-05 12:19 UTC

**Comment by goruklu** [comment] 2022-04-05 16:25
thank you @magomez
